// Package projects owns projects, which belong to organizations. Every query
// is scoped by org_id — the tenant boundary is enforced in the WHERE clause of
// every read and write, so one org can never touch another's rows.
//
// Course mapping: Chapter 7 — org scoping; Chapter 13 — pagination (offset
// here, kept simple per the project spec); Chapter 21 — service layer.
//
// Course mapping: Chapter 8 — queries generated by sqlc (internal/db). The
// methods call the generated functions and map rows into Project. UUIDs cross
// the boundary as text. The org_id scope lives in every generated query.
//
// Course mapping: Chapter 10 — soft deletes and an audit trail. Delete no
// longer removes the row; it sets deleted_at, in a transaction that also
// soft-deletes every task under the project (the cascade the row's own
// ON DELETE CASCADE foreign key used to give for free) and writes one audit
// entry. All three happen together or none does — see Service.Delete.
package projects

import (
	"context"
	"errors"
	"fmt"
	"time"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5"
	"github.com/jackc/pgx/v5/pgxpool"

	"beacon/internal/audit"
	"beacon/internal/db"
)

// Sentinel errors.
var (
	ErrNotFound = errors.New("project not found")
)

// Project belongs to an organization.
type Project struct {
	ID        string    `json:"id"`
	OrgID     string    `json:"org_id"`
	Name      string    `json:"name"`
	CreatedAt time.Time `json:"created_at"`
	UpdatedAt time.Time `json:"updated_at"`
	// DeletedAt exists so every query's column list matches db.Project's
	// exactly — see internal/db/queries/projects.sql's header. Every method
	// below already filters deleted_at IS NULL, so this is always nil for
	// anything a caller can reach; json:"-" keeps it out of the API and the
	// OpenAPI document, since always-nil is not a fact worth documenting.
	DeletedAt *time.Time `json:"-"`
}

// Repo is the projects repository backed by sqlc-generated queries. Every
// method takes org_id, and that scope lives in every generated query.
type Repo struct {
	q *db.Queries
}

func NewRepo(pool *pgxpool.Pool) *Repo { return &Repo{q: db.New(pool)} }

func toProject(p db.Project) Project {
	return Project{
		ID:        p.ID.String(),
		OrgID:     p.OrgID.String(),
		Name:      p.Name,
		CreatedAt: p.CreatedAt,
		UpdatedAt: p.UpdatedAt,
	}
}

// Create inserts a project in the given org.
func (r *Repo) Create(ctx context.Context, orgID, name string) (Project, error) {
	oid, err := uuid.Parse(orgID)
	if err != nil {
		return Project{}, fmt.Errorf("projects.Create: parse org id: %w", err)
	}
	p, err := r.q.CreateProject(ctx, db.CreateProjectParams{OrgID: oid, Name: name})
	if err != nil {
		return Project{}, fmt.Errorf("projects.Create: %w", err)
	}
	return toProject(p), nil
}

// ListByOrg returns one page of an org's projects, newest first.
func (r *Repo) ListByOrg(ctx context.Context, orgID string, limit, offset int) ([]Project, error) {
	oid, err := uuid.Parse(orgID)
	if err != nil {
		return []Project{}, nil
	}
	rows, err := r.q.ListProjectsByOrg(ctx, db.ListProjectsByOrgParams{
		OrgID:  oid,
		Limit:  int32(limit),
		Offset: int32(offset),
	})
	if err != nil {
		return nil, fmt.Errorf("projects.ListByOrg: %w", err)
	}
	out := make([]Project, 0, len(rows))
	for _, p := range rows {
		out = append(out, toProject(p))
	}
	return out, nil
}

// GetByID returns a project scoped to its org; a mismatch is ErrNotFound.
func (r *Repo) GetByID(ctx context.Context, orgID, id string) (Project, error) {
	pid, err := uuid.Parse(id)
	if err != nil {
		return Project{}, ErrNotFound
	}
	oid, err := uuid.Parse(orgID)
	if err != nil {
		return Project{}, ErrNotFound
	}
	p, err := r.q.GetProjectByID(ctx, db.GetProjectByIDParams{ID: pid, OrgID: oid})
	if err != nil {
		if errors.Is(err, pgx.ErrNoRows) {
			return Project{}, ErrNotFound
		}
		return Project{}, fmt.Errorf("projects.GetByID: %w", err)
	}
	return toProject(p), nil
}

// Update renames a project, scoped by org. ErrNotFound if no such row in org.
func (r *Repo) Update(ctx context.Context, orgID, id, name string) (Project, error) {
	pid, err := uuid.Parse(id)
	if err != nil {
		return Project{}, ErrNotFound
	}
	oid, err := uuid.Parse(orgID)
	if err != nil {
		return Project{}, ErrNotFound
	}
	p, err := r.q.UpdateProject(ctx, db.UpdateProjectParams{ID: pid, OrgID: oid, Name: name})
	if err != nil {
		if errors.Is(err, pgx.ErrNoRows) {
			return Project{}, ErrNotFound
		}
		return Project{}, fmt.Errorf("projects.Update: %w", err)
	}
	return toProject(p), nil
}

// softDelete sets deleted_at, scoped by org, using whatever Queries the
// caller hands in — the pool-bound r.q for a standalone call, or a
// transaction-bound copy when the caller (Service.Delete) needs it to commit
// or roll back with other writes. ErrNotFound if no live row matches.
func (r *Repo) softDelete(ctx context.Context, q *db.Queries, orgID, id string) error {
	pid, err := uuid.Parse(id)
	if err != nil {
		return ErrNotFound
	}
	oid, err := uuid.Parse(orgID)
	if err != nil {
		return ErrNotFound
	}
	n, err := q.SoftDeleteProject(ctx, db.SoftDeleteProjectParams{ID: pid, OrgID: oid})
	if err != nil {
		return fmt.Errorf("projects.softDelete: %w", err)
	}
	if n == 0 {
		return ErrNotFound
	}
	return nil
}

// Service holds the project business rules. Most are thin pass-throughs over
// the repo; the org scope is the rule, and it lives in every query. Delete is
// the exception — it owns a transaction, because deleting a project is three
// writes that must land together.
type Service struct {
	repo *Repo
	pool *pgxpool.Pool
}

func NewService(repo *Repo, pool *pgxpool.Pool) *Service { return &Service{repo: repo, pool: pool} }

func (s *Service) Create(ctx context.Context, orgID, name string) (Project, error) {
	return s.repo.Create(ctx, orgID, name)
}

func (s *Service) List(ctx context.Context, orgID string, limit, offset int) ([]Project, error) {
	return s.repo.ListByOrg(ctx, orgID, limit, offset)
}

func (s *Service) Get(ctx context.Context, orgID, id string) (Project, error) {
	return s.repo.GetByID(ctx, orgID, id)
}

func (s *Service) Update(ctx context.Context, orgID, id, name string) (Project, error) {
	return s.repo.Update(ctx, orgID, id, name)
}

// Delete soft-deletes a project, cascades that to every task under it — the
// ON DELETE CASCADE the schema used to provide for free now has to be written
// out, because a soft-deleted row is still there for the foreign key to see —
// and records who did it. actorID is the caller, for the audit entry.
func (s *Service) Delete(ctx context.Context, orgID, actorID, id string) error {
	tx, err := s.pool.Begin(ctx)
	if err != nil {
		return fmt.Errorf("projects.Delete: begin: %w", err)
	}
	defer tx.Rollback(ctx) //nolint:errcheck // no-op after a successful commit

	qtx := s.repo.q.WithTx(tx)
	if err := s.repo.softDelete(ctx, qtx, orgID, id); err != nil {
		return err
	}

	pid, err := uuid.Parse(id)
	if err != nil {
		return ErrNotFound
	}
	if err := qtx.SoftDeleteTasksByProject(ctx, pid); err != nil {
		return fmt.Errorf("projects.Delete: cascade to tasks: %w", err)
	}

	if err := audit.Write(ctx, qtx, audit.Entry{
		OrgID: orgID, ActorID: actorID,
		Action: "project.deleted", ResourceType: "project", ResourceID: id,
	}); err != nil {
		return fmt.Errorf("projects.Delete: %w", err)
	}

	if err := tx.Commit(ctx); err != nil {
		return fmt.Errorf("projects.Delete: commit: %w", err)
	}
	return nil
}
