// Package projects owns projects, which belong to organizations. Every query
// is scoped by org_id — the tenant boundary is enforced in the WHERE clause of
// every read and write, so one org can never touch another's rows.
//
// Course mapping: Chapter 7 — org scoping; Chapter 13 — pagination (offset
// here, kept simple per the project spec); Chapter 21 — service layer.
//
// Course mapping: Chapter 8 — queries generated by sqlc (internal/db). The
// methods call the generated functions and map rows into Project. UUIDs cross
// the boundary as text. The org_id scope lives in every generated query.
package projects

import (
	"context"
	"errors"
	"fmt"
	"time"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5"
	"github.com/jackc/pgx/v5/pgxpool"

	"beacon/internal/db"
)

// Sentinel errors.
var (
	ErrNotFound = errors.New("project not found")
)

// Project belongs to an organization.
type Project struct {
	ID        string    `json:"id"`
	OrgID     string    `json:"org_id"`
	Name      string    `json:"name"`
	CreatedAt time.Time `json:"created_at"`
	UpdatedAt time.Time `json:"updated_at"`
}

// Repo is the projects repository backed by sqlc-generated queries. Every
// method takes org_id, and that scope lives in every generated query.
type Repo struct {
	q *db.Queries
}

func NewRepo(pool *pgxpool.Pool) *Repo { return &Repo{q: db.New(pool)} }

func toProject(p db.Project) Project {
	return Project{
		ID:        p.ID.String(),
		OrgID:     p.OrgID.String(),
		Name:      p.Name,
		CreatedAt: p.CreatedAt,
		UpdatedAt: p.UpdatedAt,
	}
}

// Create inserts a project in the given org.
func (r *Repo) Create(ctx context.Context, orgID, name string) (Project, error) {
	oid, err := uuid.Parse(orgID)
	if err != nil {
		return Project{}, fmt.Errorf("projects.Create: parse org id: %w", err)
	}
	p, err := r.q.CreateProject(ctx, db.CreateProjectParams{OrgID: oid, Name: name})
	if err != nil {
		return Project{}, fmt.Errorf("projects.Create: %w", err)
	}
	return toProject(p), nil
}

// ListByOrg returns one page of an org's projects, newest first.
func (r *Repo) ListByOrg(ctx context.Context, orgID string, limit, offset int) ([]Project, error) {
	oid, err := uuid.Parse(orgID)
	if err != nil {
		return []Project{}, nil
	}
	rows, err := r.q.ListProjectsByOrg(ctx, db.ListProjectsByOrgParams{
		OrgID:  oid,
		Limit:  int32(limit),
		Offset: int32(offset),
	})
	if err != nil {
		return nil, fmt.Errorf("projects.ListByOrg: %w", err)
	}
	out := make([]Project, 0, len(rows))
	for _, p := range rows {
		out = append(out, toProject(p))
	}
	return out, nil
}

// GetByID returns a project scoped to its org; a mismatch is ErrNotFound.
func (r *Repo) GetByID(ctx context.Context, orgID, id string) (Project, error) {
	pid, err := uuid.Parse(id)
	if err != nil {
		return Project{}, ErrNotFound
	}
	oid, err := uuid.Parse(orgID)
	if err != nil {
		return Project{}, ErrNotFound
	}
	p, err := r.q.GetProjectByID(ctx, db.GetProjectByIDParams{ID: pid, OrgID: oid})
	if err != nil {
		if errors.Is(err, pgx.ErrNoRows) {
			return Project{}, ErrNotFound
		}
		return Project{}, fmt.Errorf("projects.GetByID: %w", err)
	}
	return toProject(p), nil
}

// Update renames a project, scoped by org. ErrNotFound if no such row in org.
func (r *Repo) Update(ctx context.Context, orgID, id, name string) (Project, error) {
	pid, err := uuid.Parse(id)
	if err != nil {
		return Project{}, ErrNotFound
	}
	oid, err := uuid.Parse(orgID)
	if err != nil {
		return Project{}, ErrNotFound
	}
	p, err := r.q.UpdateProject(ctx, db.UpdateProjectParams{ID: pid, OrgID: oid, Name: name})
	if err != nil {
		if errors.Is(err, pgx.ErrNoRows) {
			return Project{}, ErrNotFound
		}
		return Project{}, fmt.Errorf("projects.Update: %w", err)
	}
	return toProject(p), nil
}

// Delete removes a project, scoped by org. ErrNotFound if no such row in org.
func (r *Repo) Delete(ctx context.Context, orgID, id string) error {
	pid, err := uuid.Parse(id)
	if err != nil {
		return ErrNotFound
	}
	oid, err := uuid.Parse(orgID)
	if err != nil {
		return ErrNotFound
	}
	n, err := r.q.DeleteProject(ctx, db.DeleteProjectParams{ID: pid, OrgID: oid})
	if err != nil {
		return fmt.Errorf("projects.Delete: %w", err)
	}
	if n == 0 {
		return ErrNotFound
	}
	return nil
}

// Service holds the project business rules. Today they are thin pass-throughs
// over the repo; the org scope is the rule, and it lives in every query.
type Service struct {
	repo *Repo
}

func NewService(repo *Repo) *Service { return &Service{repo: repo} }

func (s *Service) Create(ctx context.Context, orgID, name string) (Project, error) {
	return s.repo.Create(ctx, orgID, name)
}

func (s *Service) List(ctx context.Context, orgID string, limit, offset int) ([]Project, error) {
	return s.repo.ListByOrg(ctx, orgID, limit, offset)
}

func (s *Service) Get(ctx context.Context, orgID, id string) (Project, error) {
	return s.repo.GetByID(ctx, orgID, id)
}

func (s *Service) Update(ctx context.Context, orgID, id, name string) (Project, error) {
	return s.repo.Update(ctx, orgID, id, name)
}

func (s *Service) Delete(ctx context.Context, orgID, id string) error {
	return s.repo.Delete(ctx, orgID, id)
}
