/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/healthz": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Liveness. The process is up. */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description alive */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            status?: string;
                        };
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/readyz": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Readiness. Dependencies answer. */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description ready */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description a dependency is down */
                503: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/auth/signup": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Create an account
         * @description Returns the user. It does NOT return a token — the client must log in.
         */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["SignupRequest"];
                };
            };
            responses: {
                /** @description created */
                201: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["User"];
                    };
                };
                409: components["responses"]["Conflict"];
                422: components["responses"]["Validation"];
                429: components["responses"]["RateLimited"];
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/auth/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Exchange credentials for a token */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["LoginRequest"];
                };
            };
            responses: {
                /** @description ok */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["LoginResponse"];
                    };
                };
                401: components["responses"]["Unauthorized"];
                422: components["responses"]["Validation"];
                429: components["responses"]["RateLimited"];
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** The authenticated user */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description ok */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["User"];
                    };
                };
                401: components["responses"]["Unauthorized"];
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/me/preferences": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Locale and timezone, plus what the cascade resolved for this request */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description ok */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Preferences"];
                    };
                };
                401: components["responses"]["Unauthorized"];
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /**
         * Set locale and timezone
         * @description An empty string clears the preference and hands the decision back to the cascade.
         */
        patch: {
            parameters: {
                query?: never;
                header?: {
                    /**
                     * @description A client-generated key. Repeating a request with the same key replays
                     *     the original response instead of performing the write twice.
                     */
                    "Idempotency-Key"?: components["parameters"]["IdempotencyKey"];
                };
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["PreferencesRequest"];
                };
            };
            responses: {
                /** @description ok */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Preferences"];
                    };
                };
                401: components["responses"]["Unauthorized"];
                422: components["responses"]["Validation"];
            };
        };
        trace?: never;
    };
    "/v1/orgs": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Organisations the caller belongs to, each with their role */
        get: {
            parameters: {
                query?: {
                    limit?: components["parameters"]["Limit"];
                    offset?: components["parameters"]["Offset"];
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description ok */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ListEnvelope"] & {
                            items?: components["schemas"]["OrgWithRole"][];
                        };
                    };
                };
                401: components["responses"]["Unauthorized"];
            };
        };
        put?: never;
        /**
         * Create an organisation
         * @description The caller becomes its owner.
         */
        post: {
            parameters: {
                query?: never;
                header?: {
                    /**
                     * @description A client-generated key. Repeating a request with the same key replays
                     *     the original response instead of performing the write twice.
                     */
                    "Idempotency-Key"?: components["parameters"]["IdempotencyKey"];
                };
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["CreateOrgRequest"];
                };
            };
            responses: {
                /** @description created */
                201: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Org"];
                    };
                };
                401: components["responses"]["Unauthorized"];
                422: components["responses"]["Validation"];
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/orgs/{orgID}/members": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                orgID: components["parameters"]["OrgID"];
            };
            cookie?: never;
        };
        /** Members of the organisation */
        get: {
            parameters: {
                query?: {
                    limit?: components["parameters"]["Limit"];
                    offset?: components["parameters"]["Offset"];
                };
                header?: never;
                path: {
                    orgID: components["parameters"]["OrgID"];
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description ok */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ListEnvelope"] & {
                            items?: components["schemas"]["Member"][];
                        };
                    };
                };
                403: components["responses"]["Forbidden"];
            };
        };
        put?: never;
        /**
         * Add a member by email
         * @description Requires the caller to be an owner or admin.
         */
        post: {
            parameters: {
                query?: never;
                header?: {
                    /**
                     * @description A client-generated key. Repeating a request with the same key replays
                     *     the original response instead of performing the write twice.
                     */
                    "Idempotency-Key"?: components["parameters"]["IdempotencyKey"];
                };
                path: {
                    orgID: components["parameters"]["OrgID"];
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["AddMemberRequest"];
                };
            };
            responses: {
                /** @description created */
                201: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Membership"];
                    };
                };
                403: components["responses"]["Forbidden"];
                404: components["responses"]["NotFound"];
                409: components["responses"]["Conflict"];
                422: components["responses"]["Validation"];
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/orgs/{orgID}/search": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                orgID: components["parameters"]["OrgID"];
            };
            cookie?: never;
        };
        /**
         * Search every entity in the organisation
         * @description `source` reports which engine answered — `meili` or `postgres`. The
         *     Postgres path is the fallback, and a client that shows the difference
         *     is telling the operator something true.
         */
        get: {
            parameters: {
                query: {
                    /** @description At least 2 characters. Longer than 200 is truncated, not rejected. */
                    q: string;
                    limit?: components["parameters"]["Limit"];
                    offset?: components["parameters"]["Offset"];
                };
                header?: never;
                path: {
                    orgID: components["parameters"]["OrgID"];
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description ok */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["SearchResult"];
                    };
                };
                403: components["responses"]["Forbidden"];
                422: components["responses"]["Validation"];
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/orgs/{orgID}/events": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                orgID: components["parameters"]["OrgID"];
            };
            cookie?: never;
        };
        /**
         * Server-sent events for the organisation
         * @description A `text/event-stream`. Each message is `event: <type>` with a JSON
         *     `data:` payload; comment lines (`: keep-alive`) are heartbeats.
         *
         *     Event types: `task.created`, `task.updated`, `task.deleted`. The data
         *     payload is the task.
         *
         *     A slow consumer is dropped rather than allowed to block the publisher,
         *     so a client must treat the stream as a hint to refetch, never as the
         *     only source of truth.
         */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    orgID: components["parameters"]["OrgID"];
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description the stream */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/event-stream": string;
                    };
                };
                403: components["responses"]["Forbidden"];
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/orgs/{orgID}/webhooks": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                orgID: components["parameters"]["OrgID"];
            };
            cookie?: never;
        };
        /**
         * Registered webhooks
         * @description Owner/admin only.
         */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    orgID: components["parameters"]["OrgID"];
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description ok */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ListEnvelope"] & {
                            items?: components["schemas"]["Webhook"][];
                        };
                    };
                };
                403: components["responses"]["Forbidden"];
            };
        };
        put?: never;
        /**
         * Register a webhook
         * @description The response is the only time the signing `secret` is returned in full.
         *     A client that does not show it here cannot show it later.
         */
        post: {
            parameters: {
                query?: never;
                header?: {
                    /**
                     * @description A client-generated key. Repeating a request with the same key replays
                     *     the original response instead of performing the write twice.
                     */
                    "Idempotency-Key"?: components["parameters"]["IdempotencyKey"];
                };
                path: {
                    orgID: components["parameters"]["OrgID"];
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["RegisterWebhookRequest"];
                };
            };
            responses: {
                /** @description created */
                201: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Webhook"];
                    };
                };
                403: components["responses"]["Forbidden"];
                422: components["responses"]["Validation"];
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/orgs/{orgID}/webhooks/{webhookID}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                orgID: components["parameters"]["OrgID"];
                webhookID: string;
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** Delete a webhook */
        delete: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    orgID: components["parameters"]["OrgID"];
                    webhookID: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description deleted */
                204: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                403: components["responses"]["Forbidden"];
                404: components["responses"]["NotFound"];
            };
        };
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/orgs/{orgID}/projects": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                orgID: components["parameters"]["OrgID"];
            };
            cookie?: never;
        };
        /**
         * Projects in the organisation
         * @description Two shapes behind the `new_board_ui` flag. The v2 response is the v1
         *     response plus `board: "v2"`; the client uses that marker to decide
         *     which board to render, so the server stays the single source of truth
         *     about which experiment arm the user is in.
         */
        get: {
            parameters: {
                query?: {
                    limit?: components["parameters"]["Limit"];
                    offset?: components["parameters"]["Offset"];
                };
                header?: never;
                path: {
                    orgID: components["parameters"]["OrgID"];
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description ok */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ProjectList"];
                    };
                };
                403: components["responses"]["Forbidden"];
            };
        };
        put?: never;
        /** Create a project */
        post: {
            parameters: {
                query?: never;
                header?: {
                    /**
                     * @description A client-generated key. Repeating a request with the same key replays
                     *     the original response instead of performing the write twice.
                     */
                    "Idempotency-Key"?: components["parameters"]["IdempotencyKey"];
                };
                path: {
                    orgID: components["parameters"]["OrgID"];
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["ProjectRequest"];
                };
            };
            responses: {
                /** @description created */
                201: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Project"];
                    };
                };
                403: components["responses"]["Forbidden"];
                422: components["responses"]["Validation"];
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/orgs/{orgID}/projects/{projectID}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                orgID: components["parameters"]["OrgID"];
                projectID: components["parameters"]["ProjectID"];
            };
            cookie?: never;
        };
        /**
         * One project
         * @description Answers `304` when `If-None-Match` still matches. The ETag is derived
         *     from the row's id and `updated_at`, so it changes exactly when the row
         *     does.
         */
        get: {
            parameters: {
                query?: never;
                header?: {
                    "If-None-Match"?: string;
                };
                path: {
                    orgID: components["parameters"]["OrgID"];
                    projectID: components["parameters"]["ProjectID"];
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description ok */
                200: {
                    headers: {
                        ETag?: string;
                        "Cache-Control"?: string;
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Project"];
                    };
                };
                /** @description unchanged */
                304: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                404: components["responses"]["NotFound"];
            };
        };
        put?: never;
        post?: never;
        /** Delete a project and everything in it */
        delete: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    orgID: components["parameters"]["OrgID"];
                    projectID: components["parameters"]["ProjectID"];
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description deleted */
                204: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                404: components["responses"]["NotFound"];
            };
        };
        options?: never;
        head?: never;
        /** Rename a project */
        patch: {
            parameters: {
                query?: never;
                header?: {
                    /**
                     * @description A client-generated key. Repeating a request with the same key replays
                     *     the original response instead of performing the write twice.
                     */
                    "Idempotency-Key"?: components["parameters"]["IdempotencyKey"];
                };
                path: {
                    orgID: components["parameters"]["OrgID"];
                    projectID: components["parameters"]["ProjectID"];
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["ProjectRequest"];
                };
            };
            responses: {
                /** @description ok */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Project"];
                    };
                };
                404: components["responses"]["NotFound"];
                422: components["responses"]["Validation"];
            };
        };
        trace?: never;
    };
    "/v1/orgs/{orgID}/projects/{projectID}/tasks": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                orgID: components["parameters"]["OrgID"];
                projectID: components["parameters"]["ProjectID"];
            };
            cookie?: never;
        };
        /** Tasks in the project */
        get: {
            parameters: {
                query?: {
                    limit?: components["parameters"]["Limit"];
                    offset?: components["parameters"]["Offset"];
                };
                header?: never;
                path: {
                    orgID: components["parameters"]["OrgID"];
                    projectID: components["parameters"]["ProjectID"];
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description ok */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ListEnvelope"] & {
                            items?: components["schemas"]["Task"][];
                        };
                    };
                };
                404: components["responses"]["NotFound"];
            };
        };
        put?: never;
        /** Create a task */
        post: {
            parameters: {
                query?: never;
                header?: {
                    /**
                     * @description A client-generated key. Repeating a request with the same key replays
                     *     the original response instead of performing the write twice.
                     */
                    "Idempotency-Key"?: components["parameters"]["IdempotencyKey"];
                };
                path: {
                    orgID: components["parameters"]["OrgID"];
                    projectID: components["parameters"]["ProjectID"];
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["CreateTaskRequest"];
                };
            };
            responses: {
                /** @description created */
                201: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Task"];
                    };
                };
                404: components["responses"]["NotFound"];
                422: components["responses"]["Validation"];
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/orgs/{orgID}/projects/{projectID}/tasks/{taskID}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                orgID: components["parameters"]["OrgID"];
                projectID: components["parameters"]["ProjectID"];
                taskID: components["parameters"]["TaskID"];
            };
            cookie?: never;
        };
        /** One task */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    orgID: components["parameters"]["OrgID"];
                    projectID: components["parameters"]["ProjectID"];
                    taskID: components["parameters"]["TaskID"];
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description ok */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Task"];
                    };
                };
                404: components["responses"]["NotFound"];
            };
        };
        put?: never;
        post?: never;
        /** Delete a task */
        delete: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    orgID: components["parameters"]["OrgID"];
                    projectID: components["parameters"]["ProjectID"];
                    taskID: components["parameters"]["TaskID"];
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description deleted */
                204: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                404: components["responses"]["NotFound"];
            };
        };
        options?: never;
        head?: never;
        /**
         * Update a task
         * @description A full replacement of the mutable fields: `title` and `status` are both
         *     required. Moving a card on the board is this call with a new `status`
         *     and `position`.
         */
        patch: {
            parameters: {
                query?: never;
                header?: {
                    /**
                     * @description A client-generated key. Repeating a request with the same key replays
                     *     the original response instead of performing the write twice.
                     */
                    "Idempotency-Key"?: components["parameters"]["IdempotencyKey"];
                };
                path: {
                    orgID: components["parameters"]["OrgID"];
                    projectID: components["parameters"]["ProjectID"];
                    taskID: components["parameters"]["TaskID"];
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["UpdateTaskRequest"];
                };
            };
            responses: {
                /** @description ok */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Task"];
                    };
                };
                404: components["responses"]["NotFound"];
                422: components["responses"]["Validation"];
            };
        };
        trace?: never;
    };
    "/v1/orgs/{orgID}/projects/{projectID}/tasks/{taskID}/comments": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                orgID: components["parameters"]["OrgID"];
                projectID: components["parameters"]["ProjectID"];
                taskID: components["parameters"]["TaskID"];
            };
            cookie?: never;
        };
        /** Comments on the task */
        get: {
            parameters: {
                query?: {
                    limit?: components["parameters"]["Limit"];
                    offset?: components["parameters"]["Offset"];
                };
                header?: never;
                path: {
                    orgID: components["parameters"]["OrgID"];
                    projectID: components["parameters"]["ProjectID"];
                    taskID: components["parameters"]["TaskID"];
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description ok */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ListEnvelope"] & {
                            items?: components["schemas"]["Comment"][];
                        };
                    };
                };
                404: components["responses"]["NotFound"];
            };
        };
        put?: never;
        /** Comment on the task */
        post: {
            parameters: {
                query?: never;
                header?: {
                    /**
                     * @description A client-generated key. Repeating a request with the same key replays
                     *     the original response instead of performing the write twice.
                     */
                    "Idempotency-Key"?: components["parameters"]["IdempotencyKey"];
                };
                path: {
                    orgID: components["parameters"]["OrgID"];
                    projectID: components["parameters"]["ProjectID"];
                    taskID: components["parameters"]["TaskID"];
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["CreateCommentRequest"];
                };
            };
            responses: {
                /** @description created */
                201: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Comment"];
                    };
                };
                404: components["responses"]["NotFound"];
                422: components["responses"]["Validation"];
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/orgs/{orgID}/projects/{projectID}/tasks/{taskID}/attachments": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                orgID: components["parameters"]["OrgID"];
                projectID: components["parameters"]["ProjectID"];
                taskID: components["parameters"]["TaskID"];
            };
            cookie?: never;
        };
        /** Attachments on the task */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    orgID: components["parameters"]["OrgID"];
                    projectID: components["parameters"]["ProjectID"];
                    taskID: components["parameters"]["TaskID"];
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description ok */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ListEnvelope"] & {
                            items?: components["schemas"]["Attachment"][];
                        };
                    };
                };
                404: components["responses"]["NotFound"];
                501: components["responses"]["StorageDisabled"];
            };
        };
        put?: never;
        /**
         * Reserve an attachment and get a presigned upload URL
         * @description The file never passes through this API. The client PUTs the bytes
         *     straight to `upload_url`.
         */
        post: {
            parameters: {
                query?: never;
                header?: {
                    /**
                     * @description A client-generated key. Repeating a request with the same key replays
                     *     the original response instead of performing the write twice.
                     */
                    "Idempotency-Key"?: components["parameters"]["IdempotencyKey"];
                };
                path: {
                    orgID: components["parameters"]["OrgID"];
                    projectID: components["parameters"]["ProjectID"];
                    taskID: components["parameters"]["TaskID"];
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["CreateAttachmentRequest"];
                };
            };
            responses: {
                /** @description created */
                201: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["AttachmentEnvelope"];
                    };
                };
                404: components["responses"]["NotFound"];
                422: components["responses"]["Validation"];
                501: components["responses"]["StorageDisabled"];
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/orgs/{orgID}/projects/{projectID}/tasks/{taskID}/attachments/{attachmentID}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                orgID: components["parameters"]["OrgID"];
                projectID: components["parameters"]["ProjectID"];
                taskID: components["parameters"]["TaskID"];
                attachmentID: string;
            };
            cookie?: never;
        };
        /** One attachment, with a presigned download URL */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    orgID: components["parameters"]["OrgID"];
                    projectID: components["parameters"]["ProjectID"];
                    taskID: components["parameters"]["TaskID"];
                    attachmentID: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description ok */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["AttachmentEnvelope"];
                    };
                };
                404: components["responses"]["NotFound"];
                501: components["responses"]["StorageDisabled"];
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        Error: {
            error: {
                /** @description The stable identifier. Branch on this, never on the message. */
                code: string;
                message: string;
                fields?: components["schemas"]["FieldError"][];
            };
        };
        FieldError: {
            field: string;
            rule: string;
            message: string;
        };
        ListEnvelope: {
            items: unknown[];
            limit: number;
            offset: number;
        };
        User: {
            /** Format: uuid */
            id: string;
            /** Format: email */
            email: string;
            name: string;
            /** Format: date-time */
            created_at: string;
        };
        SignupRequest: {
            /** Format: email */
            email: string;
            name?: string;
            password: string;
        };
        LoginRequest: {
            /** Format: email */
            email: string;
            password: string;
        };
        LoginResponse: {
            token: string;
            user: components["schemas"]["User"];
        };
        Preferences: {
            /** @description The stored preference. Empty means "no preference". */
            locale: string;
            /** @description An IANA name */
            timezone: string;
            /** @description What the cascade actually decided for THIS request. */
            resolved_locale: string;
            /** Format: date-time */
            now_utc: string;
            now_local: string;
            greeting: string;
            example_price: string;
        };
        PreferencesRequest: {
            locale?: string;
            timezone?: string;
        };
        /** @enum {string} */
        Role: "owner" | "admin" | "member";
        Org: {
            /** Format: uuid */
            id: string;
            name: string;
            slug: string;
            /** Format: date-time */
            created_at: string;
        };
        OrgWithRole: components["schemas"]["Org"] & {
            role: components["schemas"]["Role"];
        };
        CreateOrgRequest: {
            name: string;
        };
        Membership: {
            /** Format: uuid */
            id: string;
            /** Format: uuid */
            user_id: string;
            /** Format: uuid */
            org_id: string;
            role: components["schemas"]["Role"];
            /** Format: date-time */
            created_at: string;
        };
        Member: {
            /** Format: uuid */
            user_id: string;
            /** Format: email */
            email: string;
            name: string;
            role: components["schemas"]["Role"];
        };
        AddMemberRequest: {
            /** Format: email */
            email: string;
            role: components["schemas"]["Role"];
        };
        Project: {
            /** Format: uuid */
            id: string;
            /** Format: uuid */
            org_id: string;
            name: string;
            /** Format: date-time */
            created_at: string;
            /** Format: date-time */
            updated_at: string;
        };
        ProjectRequest: {
            name: string;
        };
        ProjectList: components["schemas"]["ListEnvelope"] & {
            items?: components["schemas"]["Project"][];
            /**
             * @description Present only on the v2 branch of the `new_board_ui` experiment.
             *     Absent means v1. The client renders the board this field names.
             * @enum {string}
             */
            board?: "v2";
        };
        /** @enum {string} */
        TaskStatus: "todo" | "in_progress" | "done";
        Task: {
            /** Format: uuid */
            id: string;
            /** Format: uuid */
            org_id: string;
            /** Format: uuid */
            project_id: string;
            title: string;
            status: components["schemas"]["TaskStatus"];
            /**
             * Format: double
             * @description A sort key within a column. It is a float so a card can be inserted
             *     between two others without renumbering the rest.
             */
            position: number;
            /** Format: date-time */
            created_at: string;
            /** Format: date-time */
            updated_at: string;
        };
        CreateTaskRequest: {
            title: string;
            status?: components["schemas"]["TaskStatus"];
            /** Format: double */
            position?: number;
        };
        UpdateTaskRequest: {
            title: string;
            status: components["schemas"]["TaskStatus"];
            /** Format: double */
            position?: number;
        };
        Comment: {
            /** Format: uuid */
            id: string;
            /** Format: uuid */
            task_id: string;
            /** Format: uuid */
            author_id: string;
            body: string;
            /** Format: date-time */
            created_at: string;
        };
        CreateCommentRequest: {
            body: string;
        };
        Attachment: {
            /** Format: uuid */
            id: string;
            /** Format: uuid */
            task_id: string;
            filename: string;
            content_type: string;
            /** Format: int64 */
            size_bytes: number;
            storage_key: string;
            /** Format: date-time */
            created_at: string;
        };
        CreateAttachmentRequest: {
            filename: string;
            content_type: string;
            /** Format: int64 */
            size: number;
        };
        AttachmentEnvelope: {
            attachment: components["schemas"]["Attachment"];
            /** @description Presigned PUT. Present on create only, and short-lived. */
            upload_url?: string;
            /** @description Presigned GET. Present on read only, and short-lived. */
            download_url?: string;
        };
        Webhook: {
            /** Format: uuid */
            id: string;
            /** Format: uuid */
            org_id: string;
            url: string;
            /** @description Returned in full only in the create response. */
            secret?: string;
            events: string[];
            active: boolean;
            /** Format: date-time */
            created_at: string;
        };
        RegisterWebhookRequest: {
            url: string;
            /** @description Empty means every event. */
            events?: string[];
        };
        SearchHit: {
            /** @description The entity type: "project", "task", "comment". */
            kind: string;
            /** Format: uuid */
            id: string;
            title: string;
            snippet: string;
            /** Format: float */
            rank?: number;
        };
        SearchResult: {
            hits: components["schemas"]["SearchHit"][];
            /**
             * @description Which engine answered. `postgres` means the fallback fired.
             * @enum {string}
             */
            source: "postgres" | "meili";
        };
    };
    responses: {
        /** @description missing or invalid token */
        Unauthorized: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["Error"];
            };
        };
        /** @description authenticated, but not allowed */
        Forbidden: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["Error"];
            };
        };
        /** @description no such resource in this organisation */
        NotFound: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["Error"];
            };
        };
        /** @description already exists */
        Conflict: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["Error"];
            };
        };
        /** @description the body failed validation; `error.fields` names each failure */
        Validation: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["Error"];
            };
        };
        /** @description too many requests */
        RateLimited: {
            headers: {
                /** @description seconds to wait before retrying */
                "Retry-After"?: number;
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["Error"];
            };
        };
        /** @description file storage is not configured on this server */
        StorageDisabled: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["Error"];
            };
        };
    };
    parameters: {
        OrgID: string;
        ProjectID: string;
        TaskID: string;
        Limit: number;
        Offset: number;
        /**
         * @description A client-generated key. Repeating a request with the same key replays
         *     the original response instead of performing the write twice.
         */
        IdempotencyKey: string;
    };
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export type operations = Record<string, never>;
