// Package tasks owns tasks and their comments. Tasks belong to projects;
// comments belong to tasks. Everything is scoped by org_id so the tenant
// boundary holds on every read and write. Status is constrained to the set
// {todo, in_progress, done}.
//
// Course mapping: Chapter 7 — org scoping; Chapter 11 — status validation;
// Chapter 13 — pagination + status filter; Chapter 21 — service layer.
//
// Course mapping: Chapter 8 — queries generated by sqlc (internal/db). The
// methods call the generated functions and map rows into Task / Comment. UUIDs
// cross the boundary as text. The org_id scope lives in every task query.
//
// Course mapping: Chapter 10 — soft deletes and an audit trail. Delete sets
// deleted_at instead of removing the row, in the same transaction as the
// audit entry recording who deleted it. Comments have no deleted_at of their
// own; ListByTask now also takes org_id, because the query behind it joins to
// tasks to check both org_id and deleted_at there — see internal/db/queries/
// tasks.sql's header for why that join exists.
package tasks

import (
	"context"
	"errors"
	"fmt"
	"time"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5"
	"github.com/jackc/pgx/v5/pgxpool"

	"go.opentelemetry.io/otel"
	"go.opentelemetry.io/otel/attribute"
	"go.opentelemetry.io/otel/trace"

	"beacon/internal/audit"
	"beacon/internal/db"
)

// Sentinel errors.
var (
	ErrNotFound      = errors.New("task not found")
	ErrInvalidStatus = errors.New("invalid task status")
	// ErrProjectNotFound is returned by the create paths when the project
	// does not exist in the caller's org — including when it exists in
	// somebody else's. CreateTask's INSERT ... SELECT writes no row in that
	// case; see internal/db/queries/tasks.sql for why the check lives there.
	// Deliberately the same answer for "no such project" and "not yours":
	// a tenant should not be able to use this endpoint to learn that another
	// tenant's project id is real.
	ErrProjectNotFound = errors.New("project not found")
)

// Valid task statuses (matches the CHECK constraint in 0001_init.up.sql).
const (
	StatusTodo       = "todo"
	StatusInProgress = "in_progress"
	StatusDone       = "done"
)

// ValidStatus reports whether s is an allowed status.
func ValidStatus(s string) bool {
	return s == StatusTodo || s == StatusInProgress || s == StatusDone
}

// Task belongs to a project (and, denormalised, an org).
type Task struct {
	ID        string    `json:"id"`
	OrgID     string    `json:"org_id"`
	ProjectID string    `json:"project_id"`
	Title     string    `json:"title"`
	Status    string    `json:"status" enum:"todo,in_progress,done"`
	Position  float64   `json:"position"`
	CreatedAt time.Time `json:"created_at"`
	UpdatedAt time.Time `json:"updated_at"`
	// DeletedAt exists so every query's column list matches db.Task's exactly
	// — see internal/db/queries/tasks.sql's header. Always nil for anything a
	// caller can reach; json:"-" keeps it out of the API.
	DeletedAt *time.Time `json:"-"`
}

// Comment belongs to a task.
type Comment struct {
	ID        string    `json:"id"`
	TaskID    string    `json:"task_id"`
	AuthorID  string    `json:"author_id"`
	Body      string    `json:"body"`
	CreatedAt time.Time `json:"created_at"`
}

// Repo is the tasks + comments repository backed by sqlc-generated queries.
// Every task method takes org_id; comment methods inherit the scope via the
// parent task lookup the service performs first.
type Repo struct {
	q *db.Queries
}

func NewRepo(pool *pgxpool.Pool) *Repo { return &Repo{q: db.New(pool)} }

func toTask(t db.Task) Task {
	return Task{
		ID:        t.ID.String(),
		OrgID:     t.OrgID.String(),
		ProjectID: t.ProjectID.String(),
		Title:     t.Title,
		Status:    t.Status,
		Position:  t.Position,
		CreatedAt: t.CreatedAt,
		UpdatedAt: t.UpdatedAt,
	}
}

func toComment(c db.Comment) Comment {
	return Comment{
		ID:        c.ID.String(),
		TaskID:    c.TaskID.String(),
		AuthorID:  c.AuthorID.String(),
		Body:      c.Body,
		CreatedAt: c.CreatedAt,
	}
}

// Create inserts a task in the given org + project.
func (r *Repo) Create(ctx context.Context, orgID, projectID, title, status string, position float64) (Task, error) {
	oid, err := uuid.Parse(orgID)
	if err != nil {
		return Task{}, fmt.Errorf("tasks.Create: parse org id: %w", err)
	}
	pid, err := uuid.Parse(projectID)
	if err != nil {
		return Task{}, fmt.Errorf("tasks.Create: parse project id: %w", err)
	}
	t, err := r.q.CreateTask(ctx, db.CreateTaskParams{
		OrgID:     oid,
		ProjectID: pid,
		Title:     title,
		Status:    status,
		Position:  position,
	})
	if err != nil {
		// No rows means the SELECT found no project with this id in this org
		// — it does not exist, or it belongs to somebody else. Both answer
		// ErrProjectNotFound; the query's header explains why they must.
		if errors.Is(err, pgx.ErrNoRows) {
			return Task{}, ErrProjectNotFound
		}
		return Task{}, fmt.Errorf("tasks.Create: %w", err)
	}
	return toTask(t), nil
}

// ListByProject returns one page of a project's tasks, optionally filtered by
// status. Scoped by org. An empty status means "any status".
func (r *Repo) ListByProject(ctx context.Context, orgID, projectID, status string, limit, offset int) ([]Task, error) {
	oid, err := uuid.Parse(orgID)
	if err != nil {
		return []Task{}, nil
	}
	pid, err := uuid.Parse(projectID)
	if err != nil {
		return []Task{}, nil
	}

	// A nil status pointer makes the status clause a no-op (any status).
	var statusArg *string
	if status != "" {
		statusArg = &status
	}

	rows, err := r.q.ListTasksByProject(ctx, db.ListTasksByProjectParams{
		OrgID:     oid,
		ProjectID: pid,
		Status:    statusArg,
		Limit:     int32(limit),
		Offset:    int32(offset),
	})
	if err != nil {
		return nil, fmt.Errorf("tasks.ListByProject: %w", err)
	}
	out := make([]Task, 0, len(rows))
	for _, t := range rows {
		out = append(out, toTask(t))
	}
	return out, nil
}

// GetByID returns a task scoped to its org; a mismatch is ErrNotFound.
func (r *Repo) GetByID(ctx context.Context, orgID, id string) (Task, error) {
	tid, err := uuid.Parse(id)
	if err != nil {
		return Task{}, ErrNotFound
	}
	oid, err := uuid.Parse(orgID)
	if err != nil {
		return Task{}, ErrNotFound
	}
	t, err := r.q.GetTaskByID(ctx, db.GetTaskByIDParams{ID: tid, OrgID: oid})
	if err != nil {
		if errors.Is(err, pgx.ErrNoRows) {
			return Task{}, ErrNotFound
		}
		return Task{}, fmt.Errorf("tasks.GetByID: %w", err)
	}
	return toTask(t), nil
}

// Update changes a task's title, status, and position, scoped by org.
func (r *Repo) Update(ctx context.Context, orgID, id, title, status string, position float64) (Task, error) {
	tid, err := uuid.Parse(id)
	if err != nil {
		return Task{}, ErrNotFound
	}
	oid, err := uuid.Parse(orgID)
	if err != nil {
		return Task{}, ErrNotFound
	}
	t, err := r.q.UpdateTask(ctx, db.UpdateTaskParams{
		ID:       tid,
		OrgID:    oid,
		Title:    title,
		Status:   status,
		Position: position,
	})
	if err != nil {
		if errors.Is(err, pgx.ErrNoRows) {
			return Task{}, ErrNotFound
		}
		return Task{}, fmt.Errorf("tasks.Update: %w", err)
	}
	return toTask(t), nil
}

// softDelete sets deleted_at, scoped by org, using whatever Queries the
// caller hands in — see projects.Repo.softDelete's comment for why that
// parameter exists. ErrNotFound if no live row matches.
func (r *Repo) softDelete(ctx context.Context, q *db.Queries, orgID, id string) error {
	tid, err := uuid.Parse(id)
	if err != nil {
		return ErrNotFound
	}
	oid, err := uuid.Parse(orgID)
	if err != nil {
		return ErrNotFound
	}
	n, err := q.SoftDeleteTask(ctx, db.SoftDeleteTaskParams{ID: tid, OrgID: oid})
	if err != nil {
		return fmt.Errorf("tasks.softDelete: %w", err)
	}
	if n == 0 {
		return ErrNotFound
	}
	return nil
}

// CreateComment inserts a comment on a task.
func (r *Repo) CreateComment(ctx context.Context, taskID, authorID, body string) (Comment, error) {
	tid, err := uuid.Parse(taskID)
	if err != nil {
		return Comment{}, fmt.Errorf("tasks.CreateComment: parse task id: %w", err)
	}
	aid, err := uuid.Parse(authorID)
	if err != nil {
		return Comment{}, fmt.Errorf("tasks.CreateComment: parse author id: %w", err)
	}
	c, err := r.q.CreateComment(ctx, db.CreateCommentParams{TaskID: tid, AuthorID: aid, Body: body})
	if err != nil {
		return Comment{}, fmt.Errorf("tasks.CreateComment: %w", err)
	}
	return toComment(c), nil
}

// ListByTask returns every comment on a task, oldest first. Scoped by org
// through a join to tasks, which is also where a soft-deleted task's comments
// stop being visible — see the query's own header.
func (r *Repo) ListByTask(ctx context.Context, orgID, taskID string) ([]Comment, error) {
	tid, err := uuid.Parse(taskID)
	if err != nil {
		return []Comment{}, nil
	}
	oid, err := uuid.Parse(orgID)
	if err != nil {
		return []Comment{}, nil
	}
	rows, err := r.q.ListCommentsByTask(ctx, db.ListCommentsByTaskParams{TaskID: tid, OrgID: oid})
	if err != nil {
		return nil, fmt.Errorf("tasks.ListByTask: %w", err)
	}
	out := make([]Comment, 0, len(rows))
	for _, c := range rows {
		out = append(out, toComment(c))
	}
	return out, nil
}

// Service holds the task business rules: status validation and org scoping.
type Service struct {
	repo *Repo
	pool *pgxpool.Pool
}

func NewService(repo *Repo, pool *pgxpool.Pool) *Service { return &Service{repo: repo, pool: pool} }

// Create makes a new task. Status defaults to "todo"; a supplied status must
// be valid.
// Create validates and inserts a task.
//
// Ch 36 — the service-layer span. Two details matter and both are easy to get
// wrong. First, USE the ctx that Start returns: pass the original one
// downstream and the child spans become orphans and the tree is a lie. Second,
// the attributes are log-grade — org and project ids, never a title, an email
// or anything else a person wrote. Spans go to a third-party backend and get
// read by anyone with a login.
func (s *Service) Create(ctx context.Context, orgID, projectID, title, status string, position float64) (Task, error) {
	ctx, span := otel.Tracer("beacon/tasks").Start(ctx, "tasks.Create",
		trace.WithAttributes(
			attribute.String("org_id", orgID),
			attribute.String("project_id", projectID),
		),
	)
	defer span.End()

	if status == "" {
		status = StatusTodo
	}
	if !ValidStatus(status) {
		span.RecordError(ErrInvalidStatus)
		return Task{}, ErrInvalidStatus
	}
	return s.repo.Create(ctx, orgID, projectID, title, status, position)
}

// List returns a page of a project's tasks, optionally filtered by status.
func (s *Service) List(ctx context.Context, orgID, projectID, status string, limit, offset int) ([]Task, error) {
	if status != "" && !ValidStatus(status) {
		return nil, ErrInvalidStatus
	}
	return s.repo.ListByProject(ctx, orgID, projectID, status, limit, offset)
}

// Get returns a single task, scoped by org.
func (s *Service) Get(ctx context.Context, orgID, id string) (Task, error) {
	return s.repo.GetByID(ctx, orgID, id)
}

// Update changes a task's title/status/position after validating status.
func (s *Service) Update(ctx context.Context, orgID, id, title, status string, position float64) (Task, error) {
	if !ValidStatus(status) {
		return Task{}, ErrInvalidStatus
	}
	return s.repo.Update(ctx, orgID, id, title, status, position)
}

// Delete soft-deletes a task, scoped by org, and records who did it in the
// same transaction — either both land or neither does. actorID is the
// caller, for the audit entry.
func (s *Service) Delete(ctx context.Context, orgID, actorID, id string) error {
	tx, err := s.pool.Begin(ctx)
	if err != nil {
		return fmt.Errorf("tasks.Delete: begin: %w", err)
	}
	defer tx.Rollback(ctx) //nolint:errcheck // no-op after a successful commit

	qtx := s.repo.q.WithTx(tx)
	if err := s.repo.softDelete(ctx, qtx, orgID, id); err != nil {
		return err
	}

	if err := audit.Write(ctx, qtx, audit.Entry{
		OrgID: orgID, ActorID: actorID,
		Action: "task.deleted", ResourceType: "task", ResourceID: id,
	}); err != nil {
		return fmt.Errorf("tasks.Delete: %w", err)
	}

	if err := tx.Commit(ctx); err != nil {
		return fmt.Errorf("tasks.Delete: commit: %w", err)
	}
	return nil
}

// AddComment confirms the task exists in the caller's org, then writes the
// comment. Scoping the parent task by org keeps comments tenant-safe.
func (s *Service) AddComment(ctx context.Context, orgID, taskID, authorID, body string) (Comment, error) {
	if _, err := s.repo.GetByID(ctx, orgID, taskID); err != nil {
		return Comment{}, err
	}
	return s.repo.CreateComment(ctx, taskID, authorID, body)
}

// Comments lists a task's comments after confirming the task is in the org.
func (s *Service) Comments(ctx context.Context, orgID, taskID string) ([]Comment, error) {
	if _, err := s.repo.GetByID(ctx, orgID, taskID); err != nil {
		return nil, err
	}
	return s.repo.ListByTask(ctx, orgID, taskID)
}
