// Package tasks owns tasks and their comments. Tasks belong to projects;
// comments belong to tasks. Everything is scoped by org_id so the tenant
// boundary holds on every read and write. Status is constrained to the set
// {todo, in_progress, done}.
//
// Course mapping: Chapter 7 — org scoping; Chapter 11 — status validation;
// Chapter 13 — pagination + status filter; Chapter 21 — service layer.
//
// Course mapping: Chapter 8 — queries generated by sqlc (internal/db). The
// methods call the generated functions and map rows into Task / Comment. UUIDs
// cross the boundary as text. The org_id scope lives in every task query.
//
// Course mapping: Chapter 10 — soft deletes and an audit trail. Delete sets
// deleted_at instead of removing the row, in the same transaction as the
// audit entry recording who deleted it. Comments have their own deleted_at as
// of 0010, added with the DELETE endpoint whose absence had been the reason
// they went without one; ListByTask also takes org_id, because the query
// behind it joins to tasks to check org_id and the task's deleted_at there —
// see internal/db/queries/tasks.sql's header for why that join exists.
//
// Who may do what to a comment: the author edits their own and nobody else's,
// because an admin rewriting somebody's words under their name has no
// legitimate use. Deleting is wider — the author, or an org admin/owner, so a
// leaked secret is removable by someone other than whoever posted it.
package tasks

import (
	"context"
	"errors"
	"fmt"
	"time"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5"
	"github.com/jackc/pgx/v5/pgxpool"

	"go.opentelemetry.io/otel"
	"go.opentelemetry.io/otel/attribute"
	"go.opentelemetry.io/otel/trace"

	"beacon/internal/audit"
	"beacon/internal/db"
	"beacon/internal/orgs"
)

// Sentinel errors.
var (
	ErrNotFound      = errors.New("task not found")
	ErrInvalidStatus = errors.New("invalid task status")
	// ErrProjectNotFound is returned by the create paths when the project
	// does not exist in the caller's org — including when it exists in
	// somebody else's. CreateTask's INSERT ... SELECT writes no row in that
	// case; see internal/db/queries/tasks.sql for why the check lives there.
	// Deliberately the same answer for "no such project" and "not yours":
	// a tenant should not be able to use this endpoint to learn that another
	// tenant's project id is real.
	ErrProjectNotFound = errors.New("project not found")
	// ErrCommentNotFound covers a comment that does not exist, is already
	// deleted, or belongs to another org — one answer for all three, so the
	// endpoint cannot be used to probe for real comment ids.
	ErrCommentNotFound = errors.New("comment not found")
	// ErrNotCommentAuthor is an edit attempt on somebody else's comment. It is
	// deliberately distinct from ErrCommentNotFound: the comment IS there and
	// the caller can already read it, so pretending otherwise would just make
	// the UI unexplainable. Nothing is disclosed that a read did not disclose.
	ErrNotCommentAuthor = errors.New("only the author can edit a comment")
	// ErrCannotDeleteComment is a delete attempt by someone who is neither the
	// author nor an org admin.
	ErrCannotDeleteComment = errors.New("only the author or an admin can delete a comment")
)

// Valid task statuses (matches the CHECK constraint in 0001_init.up.sql).
const (
	StatusTodo       = "todo"
	StatusInProgress = "in_progress"
	StatusDone       = "done"
)

// ValidStatus reports whether s is an allowed status.
func ValidStatus(s string) bool {
	return s == StatusTodo || s == StatusInProgress || s == StatusDone
}

// Task belongs to a project (and, denormalised, an org).
type Task struct {
	ID        string    `json:"id"`
	OrgID     string    `json:"org_id"`
	ProjectID string    `json:"project_id"`
	Title     string    `json:"title"`
	Status    string    `json:"status" enum:"todo,in_progress,done"`
	Position  float64   `json:"position"`
	CreatedAt time.Time `json:"created_at"`
	UpdatedAt time.Time `json:"updated_at"`
	// DeletedAt exists so every query's column list matches db.Task's exactly
	// — see internal/db/queries/tasks.sql's header. Always nil for anything a
	// caller can reach; json:"-" keeps it out of the API.
	DeletedAt *time.Time `json:"-"`
}

// Comment belongs to a task.
type Comment struct {
	ID        string    `json:"id"`
	TaskID    string    `json:"task_id"`
	AuthorID  string    `json:"author_id"`
	Body      string    `json:"body"`
	CreatedAt time.Time `json:"created_at"`
	UpdatedAt time.Time `json:"updated_at"`
	// Edited is derived, not stored: it is UpdatedAt being meaningfully later
	// than CreatedAt. Computed here so every client marks an edited comment the
	// same way — left to the browser, one of them compares two timestamps with
	// the wrong precision and quietly labels every comment edited.
	Edited bool `json:"edited"`
}

// Repo is the tasks + comments repository backed by sqlc-generated queries.
// Every task method takes org_id; comment methods inherit the scope via the
// parent task lookup the service performs first.
type Repo struct {
	q *db.Queries
}

func NewRepo(pool *pgxpool.Pool) *Repo { return &Repo{q: db.New(pool)} }

func toTask(t db.Task) Task {
	return Task{
		ID:        t.ID.String(),
		OrgID:     t.OrgID.String(),
		ProjectID: t.ProjectID.String(),
		Title:     t.Title,
		Status:    t.Status,
		Position:  t.Position,
		CreatedAt: t.CreatedAt,
		UpdatedAt: t.UpdatedAt,
	}
}

// newComment is the one place a Comment is assembled.
//
// sqlc emits a distinct row struct per query — db.Comment, GetCommentByIDRow,
// UpdateCommentRow, ListCommentsByTaskRow — with identical fields and no
// common interface, so every caller would otherwise repeat this mapping and
// the Edited rule with it. Taking the fields instead of a row type keeps that
// rule in exactly one place.
func newComment(id, taskID, authorID uuid.UUID, body string, created, updated time.Time) Comment {
	return Comment{
		ID:        id.String(),
		TaskID:    taskID.String(),
		AuthorID:  authorID.String(),
		Body:      body,
		CreatedAt: created,
		UpdatedAt: updated,
		// Exact inequality, no tolerance window.
		//
		// Postgres now() is the TRANSACTION timestamp, not the clock read at
		// each column, so an insert sets created_at and updated_at from the
		// same value and they come back byte-identical — verified against a
		// real database rather than assumed. An edit runs in a later
		// transaction and therefore always differs.
		//
		// The first version of this allowed a second of slack, to be "safe"
		// about the two defaults racing. They cannot race, and the slack meant
		// a correction made within a second of posting — the most common kind
		// — was silently not marked as an edit.
		Edited: !updated.Equal(created),
	}
}

func toComment(c db.CreateCommentRow) Comment {
	return newComment(c.ID, c.TaskID, c.AuthorID, c.Body, c.CreatedAt, c.UpdatedAt)
}

// Create inserts a task in the given org + project.
func (r *Repo) Create(ctx context.Context, orgID, projectID, title, status string, position float64) (Task, error) {
	oid, err := uuid.Parse(orgID)
	if err != nil {
		return Task{}, fmt.Errorf("tasks.Create: parse org id: %w", err)
	}
	pid, err := uuid.Parse(projectID)
	if err != nil {
		return Task{}, fmt.Errorf("tasks.Create: parse project id: %w", err)
	}
	t, err := r.q.CreateTask(ctx, db.CreateTaskParams{
		OrgID:     oid,
		ProjectID: pid,
		Title:     title,
		Status:    status,
		Position:  position,
	})
	if err != nil {
		// No rows means the SELECT found no project with this id in this org
		// — it does not exist, or it belongs to somebody else. Both answer
		// ErrProjectNotFound; the query's header explains why they must.
		if errors.Is(err, pgx.ErrNoRows) {
			return Task{}, ErrProjectNotFound
		}
		return Task{}, fmt.Errorf("tasks.Create: %w", err)
	}
	return toTask(t), nil
}

// ListByProject returns one page of a project's tasks, optionally filtered by
// status. Scoped by org. An empty status means "any status".
func (r *Repo) ListByProject(ctx context.Context, orgID, projectID, status string, limit, offset int) ([]Task, error) {
	oid, err := uuid.Parse(orgID)
	if err != nil {
		return []Task{}, nil
	}
	pid, err := uuid.Parse(projectID)
	if err != nil {
		return []Task{}, nil
	}

	// A nil status pointer makes the status clause a no-op (any status).
	var statusArg *string
	if status != "" {
		statusArg = &status
	}

	rows, err := r.q.ListTasksByProject(ctx, db.ListTasksByProjectParams{
		OrgID:     oid,
		ProjectID: pid,
		Status:    statusArg,
		Limit:     int32(limit),
		Offset:    int32(offset),
	})
	if err != nil {
		return nil, fmt.Errorf("tasks.ListByProject: %w", err)
	}
	out := make([]Task, 0, len(rows))
	for _, t := range rows {
		out = append(out, toTask(t))
	}
	return out, nil
}

// GetByID returns a task scoped to its org; a mismatch is ErrNotFound.
func (r *Repo) GetByID(ctx context.Context, orgID, id string) (Task, error) {
	tid, err := uuid.Parse(id)
	if err != nil {
		return Task{}, ErrNotFound
	}
	oid, err := uuid.Parse(orgID)
	if err != nil {
		return Task{}, ErrNotFound
	}
	t, err := r.q.GetTaskByID(ctx, db.GetTaskByIDParams{ID: tid, OrgID: oid})
	if err != nil {
		if errors.Is(err, pgx.ErrNoRows) {
			return Task{}, ErrNotFound
		}
		return Task{}, fmt.Errorf("tasks.GetByID: %w", err)
	}
	return toTask(t), nil
}

// Update changes a task's title, status, and position, scoped by org.
func (r *Repo) Update(ctx context.Context, orgID, id, title, status string, position float64) (Task, error) {
	tid, err := uuid.Parse(id)
	if err != nil {
		return Task{}, ErrNotFound
	}
	oid, err := uuid.Parse(orgID)
	if err != nil {
		return Task{}, ErrNotFound
	}
	t, err := r.q.UpdateTask(ctx, db.UpdateTaskParams{
		ID:       tid,
		OrgID:    oid,
		Title:    title,
		Status:   status,
		Position: position,
	})
	if err != nil {
		if errors.Is(err, pgx.ErrNoRows) {
			return Task{}, ErrNotFound
		}
		return Task{}, fmt.Errorf("tasks.Update: %w", err)
	}
	return toTask(t), nil
}

// softDelete sets deleted_at, scoped by org, using whatever Queries the
// caller hands in — see projects.Repo.softDelete's comment for why that
// parameter exists. ErrNotFound if no live row matches.
func (r *Repo) softDelete(ctx context.Context, q *db.Queries, orgID, id string) error {
	tid, err := uuid.Parse(id)
	if err != nil {
		return ErrNotFound
	}
	oid, err := uuid.Parse(orgID)
	if err != nil {
		return ErrNotFound
	}
	n, err := q.SoftDeleteTask(ctx, db.SoftDeleteTaskParams{ID: tid, OrgID: oid})
	if err != nil {
		return fmt.Errorf("tasks.softDelete: %w", err)
	}
	if n == 0 {
		return ErrNotFound
	}
	return nil
}

// CreateComment inserts a comment on a task.
func (r *Repo) CreateComment(ctx context.Context, taskID, authorID, body string) (Comment, error) {
	tid, err := uuid.Parse(taskID)
	if err != nil {
		return Comment{}, fmt.Errorf("tasks.CreateComment: parse task id: %w", err)
	}
	aid, err := uuid.Parse(authorID)
	if err != nil {
		return Comment{}, fmt.Errorf("tasks.CreateComment: parse author id: %w", err)
	}
	c, err := r.q.CreateComment(ctx, db.CreateCommentParams{TaskID: tid, AuthorID: aid, Body: body})
	if err != nil {
		return Comment{}, fmt.Errorf("tasks.CreateComment: %w", err)
	}
	return toComment(c), nil
}

// ListByTask returns every comment on a task, oldest first. Scoped by org
// through a join to tasks, which is also where a soft-deleted task's comments
// stop being visible — see the query's own header.
// getComment reads one comment, scoped to the org through its parent task.
// Both mutating paths call this first: an edit needs the author id to compare
// against the caller, and a delete needs it to decide between "your own" and
// "moderation".
func (r *Repo) getComment(ctx context.Context, orgID, commentID string) (Comment, error) {
	cid, err := uuid.Parse(commentID)
	if err != nil {
		return Comment{}, ErrCommentNotFound
	}
	oid, err := uuid.Parse(orgID)
	if err != nil {
		return Comment{}, ErrCommentNotFound
	}
	c, err := r.q.GetCommentByID(ctx, db.GetCommentByIDParams{ID: cid, OrgID: oid})
	if err != nil {
		if errors.Is(err, pgx.ErrNoRows) {
			return Comment{}, ErrCommentNotFound
		}
		return Comment{}, fmt.Errorf("tasks.getComment: %w", err)
	}
	return newComment(c.ID, c.TaskID, c.AuthorID, c.Body, c.CreatedAt, c.UpdatedAt), nil
}

func (r *Repo) updateComment(ctx context.Context, orgID, commentID, authorID, body string) (Comment, error) {
	cid, err := uuid.Parse(commentID)
	if err != nil {
		return Comment{}, ErrCommentNotFound
	}
	oid, err := uuid.Parse(orgID)
	if err != nil {
		return Comment{}, ErrCommentNotFound
	}
	aid, err := uuid.Parse(authorID)
	if err != nil {
		return Comment{}, ErrNotCommentAuthor
	}
	c, err := r.q.UpdateComment(ctx, db.UpdateCommentParams{
		ID: cid, OrgID: oid, AuthorID: aid, Body: body,
	})
	if err != nil {
		// The query carries the author check too, so no rows here means the
		// caller is not the author — the service already returned a clearer
		// error for that, and this covers a racing delete in between.
		if errors.Is(err, pgx.ErrNoRows) {
			return Comment{}, ErrCommentNotFound
		}
		return Comment{}, fmt.Errorf("tasks.updateComment: %w", err)
	}
	return newComment(c.ID, c.TaskID, c.AuthorID, c.Body, c.CreatedAt, c.UpdatedAt), nil
}

// softDeleteComment takes a caller-supplied Queries so the delete and its
// audit entry commit together.
func (r *Repo) softDeleteComment(ctx context.Context, q *db.Queries, orgID, commentID string) error {
	cid, err := uuid.Parse(commentID)
	if err != nil {
		return ErrCommentNotFound
	}
	oid, err := uuid.Parse(orgID)
	if err != nil {
		return ErrCommentNotFound
	}
	n, err := q.SoftDeleteComment(ctx, db.SoftDeleteCommentParams{ID: cid, OrgID: oid})
	if err != nil {
		return fmt.Errorf("tasks.softDeleteComment: %w", err)
	}
	if n == 0 {
		return ErrCommentNotFound
	}
	return nil
}

func (r *Repo) ListByTask(ctx context.Context, orgID, taskID string) ([]Comment, error) {
	tid, err := uuid.Parse(taskID)
	if err != nil {
		return []Comment{}, nil
	}
	oid, err := uuid.Parse(orgID)
	if err != nil {
		return []Comment{}, nil
	}
	rows, err := r.q.ListCommentsByTask(ctx, db.ListCommentsByTaskParams{TaskID: tid, OrgID: oid})
	if err != nil {
		return nil, fmt.Errorf("tasks.ListByTask: %w", err)
	}
	out := make([]Comment, 0, len(rows))
	for _, c := range rows {
		out = append(out, newComment(c.ID, c.TaskID, c.AuthorID, c.Body, c.CreatedAt, c.UpdatedAt))
	}
	return out, nil
}

// Service holds the task business rules: status validation and org scoping.
type Service struct {
	repo *Repo
	pool *pgxpool.Pool
}

func NewService(repo *Repo, pool *pgxpool.Pool) *Service { return &Service{repo: repo, pool: pool} }

// Create makes a new task. Status defaults to "todo"; a supplied status must
// be valid.
// Create validates and inserts a task.
//
// Ch 36 — the service-layer span. Two details matter and both are easy to get
// wrong. First, USE the ctx that Start returns: pass the original one
// downstream and the child spans become orphans and the tree is a lie. Second,
// the attributes are log-grade — org and project ids, never a title, an email
// or anything else a person wrote. Spans go to a third-party backend and get
// read by anyone with a login.
func (s *Service) Create(ctx context.Context, orgID, projectID, title, status string, position float64) (Task, error) {
	ctx, span := otel.Tracer("beacon/tasks").Start(ctx, "tasks.Create",
		trace.WithAttributes(
			attribute.String("org_id", orgID),
			attribute.String("project_id", projectID),
		),
	)
	defer span.End()

	if status == "" {
		status = StatusTodo
	}
	if !ValidStatus(status) {
		span.RecordError(ErrInvalidStatus)
		return Task{}, ErrInvalidStatus
	}
	return s.repo.Create(ctx, orgID, projectID, title, status, position)
}

// List returns a page of a project's tasks, optionally filtered by status.
func (s *Service) List(ctx context.Context, orgID, projectID, status string, limit, offset int) ([]Task, error) {
	if status != "" && !ValidStatus(status) {
		return nil, ErrInvalidStatus
	}
	return s.repo.ListByProject(ctx, orgID, projectID, status, limit, offset)
}

// Get returns a single task, scoped by org.
func (s *Service) Get(ctx context.Context, orgID, id string) (Task, error) {
	return s.repo.GetByID(ctx, orgID, id)
}

// Update changes a task's title/status/position after validating status.
func (s *Service) Update(ctx context.Context, orgID, id, title, status string, position float64) (Task, error) {
	if !ValidStatus(status) {
		return Task{}, ErrInvalidStatus
	}
	return s.repo.Update(ctx, orgID, id, title, status, position)
}

// Delete soft-deletes a task, scoped by org, and records who did it in the
// same transaction — either both land or neither does. actorID is the
// caller, for the audit entry.
func (s *Service) Delete(ctx context.Context, orgID, actorID, id string) error {
	tx, err := s.pool.Begin(ctx)
	if err != nil {
		return fmt.Errorf("tasks.Delete: begin: %w", err)
	}
	defer tx.Rollback(ctx) //nolint:errcheck // no-op after a successful commit

	qtx := s.repo.q.WithTx(tx)
	if err := s.repo.softDelete(ctx, qtx, orgID, id); err != nil {
		return err
	}

	if err := audit.Write(ctx, qtx, audit.Entry{
		OrgID: orgID, ActorID: actorID,
		Action: "task.deleted", ResourceType: "task", ResourceID: id,
	}); err != nil {
		return fmt.Errorf("tasks.Delete: %w", err)
	}

	if err := tx.Commit(ctx); err != nil {
		return fmt.Errorf("tasks.Delete: commit: %w", err)
	}
	return nil
}

// AddComment confirms the task exists in the caller's org, then writes the
// comment. Scoping the parent task by org keeps comments tenant-safe.
func (s *Service) AddComment(ctx context.Context, orgID, taskID, authorID, body string) (Comment, error) {
	if _, err := s.repo.GetByID(ctx, orgID, taskID); err != nil {
		return Comment{}, err
	}
	return s.repo.CreateComment(ctx, taskID, authorID, body)
}

// Comments lists a task's comments after confirming the task is in the org.
func (s *Service) Comments(ctx context.Context, orgID, taskID string) ([]Comment, error) {
	if _, err := s.repo.GetByID(ctx, orgID, taskID); err != nil {
		return nil, err
	}
	return s.repo.ListByTask(ctx, orgID, taskID)
}

// UpdateComment rewrites a comment's body. Only its author may do this.
//
// Not admins, deliberately, and this is the one place the two verbs part
// company: an admin deleting a comment removes something from the record,
// which is moderation; an admin EDITING one would put words in somebody's
// mouth under that person's name. There is no legitimate version of that, so
// the capability does not exist rather than being guarded by a role check.
func (s *Service) UpdateComment(ctx context.Context, orgID, commentID, actorID, body string) (Comment, error) {
	existing, err := s.repo.getComment(ctx, orgID, commentID)
	if err != nil {
		return Comment{}, err
	}
	if existing.AuthorID != actorID {
		return Comment{}, ErrNotCommentAuthor
	}
	return s.repo.updateComment(ctx, orgID, commentID, actorID, body)
}

// DeleteComment soft-deletes a comment. The author may delete their own; an
// org admin or owner may delete anyone's, which is the moderation path — a
// leaked secret or an abusive message has to be removable by someone other
// than the person who posted it.
//
// The delete and its audit entry share one transaction, the same shape
// Delete uses: an admin removing someone else's words is exactly the event
// Chapter 10's audit log exists to answer "who did this, and when" about.
func (s *Service) DeleteComment(ctx context.Context, orgID, commentID, actorID, actorRole string) error {
	existing, err := s.repo.getComment(ctx, orgID, commentID)
	if err != nil {
		return err
	}
	if existing.AuthorID != actorID && orgs.RoleRank(actorRole) < orgs.RoleRank(orgs.RoleAdmin) {
		return ErrCannotDeleteComment
	}

	tx, err := s.pool.Begin(ctx)
	if err != nil {
		return fmt.Errorf("tasks.DeleteComment: begin: %w", err)
	}
	defer tx.Rollback(ctx) //nolint:errcheck // no-op after a successful commit

	qtx := s.repo.q.WithTx(tx)
	if err := s.repo.softDeleteComment(ctx, qtx, orgID, commentID); err != nil {
		return err
	}

	if err := audit.Write(ctx, qtx, audit.Entry{
		OrgID: orgID, ActorID: actorID,
		Action: "comment.deleted", ResourceType: "comment", ResourceID: commentID,
	}); err != nil {
		return fmt.Errorf("tasks.DeleteComment: %w", err)
	}

	if err := tx.Commit(ctx); err != nil {
		return fmt.Errorf("tasks.DeleteComment: commit: %w", err)
	}
	return nil
}
