/**
 * tokens.source.ts -> tokens.gen.css + tokens.gen.ts
 *
 * The CSS file feeds Tailwind's @theme inline; the TS file gives charts,
 * canvas and tests a typed name for every color, so nothing ever hardcodes a
 * hex outside the source file. (production-frontend ch12)
 *
 * Both outputs are gitignored (*.gen.css, *.gen.ts) — generated, never
 * committed, never hand-edited. `npm run build` and `npm run dev` both run
 * this first, so every entry point regenerates from tokens.source.ts rather
 * than trusting whatever copy happens to be sitting on disk. That is the
 * point, not an accident: `dev` used to skip it, which worked on a machine
 * that had already run `build` at least once and left the files behind, and
 * failed outright on a genuinely fresh checkout — which is exactly what a CI
 * runner is. `go test ./...`'s deadlock-from-a-shared-database bug and this
 * one are the same shape of mistake: something that only works if a prior,
 * uncoordinated step happened to leave the right state lying around.
 */
import { writeFileSync } from "node:fs";
import { tokens } from "../src/design/tokens.source";
import { checkContrast, pairCount } from "./contrast";

// Refuse to emit a palette that cannot be read. (ch10)
const failures = checkContrast();
if (failures.length > 0) {
  console.error(`\ncontrast: ${failures.length} of ${pairCount} pairs fail\n`);
  for (const f of failures) console.error("  " + f);
  console.error("\nFix tokens.source.ts. Nothing was written.\n");
  process.exit(1);
}

const names = Object.keys(tokens) as (keyof typeof tokens)[];

const cssVars = (theme: "light" | "dark") =>
  names.map((n) => `  --${n}: ${tokens[n][theme]};`).join("\n");

const css = `/* GENERATED by scripts/gen-tokens.ts — do not edit. */
:root[data-theme="light"] {
${cssVars("light")}
}
:root[data-theme="dark"] {
${cssVars("dark")}
}
`;

const ts = `// GENERATED by scripts/gen-tokens.ts — do not edit.
export const tokenNames = ${JSON.stringify(names)} as const;
export type TokenName = (typeof tokenNames)[number];
export const tokenValues = ${JSON.stringify(
  Object.fromEntries(
    names.map((n) => [n, { light: tokens[n].light, dark: tokens[n].dark, why: tokens[n].why }]),
  ),
  null,
  2,
)} as const;
export function cssVar(name: TokenName): string {
  return \`var(--\${name})\`;
}
`;

writeFileSync("src/styles/tokens.gen.css", css);
writeFileSync("src/design/tokens.gen.ts", ts);
console.log(`tokens: ${names.length} roles, ${pairCount} contrast pairs pass -> tokens.gen.css, tokens.gen.ts`);
