// Package attachments owns file-attachment metadata for tasks. The bytes live
// in object storage (see internal/storage); this package only records the row:
// filename, content type, size, and the generated storage_key the presigned
// URLs point at.
//
// Course mapping: Chapter 22 — file uploads. The attachments table predates
// this phase (migration 0001); we add the domain layer over it now.
//
// NOTE: attachments has no org_id column of its own (it hangs off task_id), so
// every query joins through tasks and filters on tasks.org_id — the tenant
// boundary still holds on every read and write.
//
// Course mapping: Chapter 8 — queries generated by sqlc (internal/db). The
// methods call the generated functions and map rows into Attachment; UUIDs
// cross the boundary as text.
package attachments

import (
	"context"
	"crypto/rand"
	"encoding/hex"
	"errors"
	"fmt"
	"path"
	"time"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5"
	"github.com/jackc/pgx/v5/pgxpool"

	"beacon/internal/db"
)

// ErrNotFound is returned when no attachment matches in the caller's org.
var ErrNotFound = errors.New("attachment not found")

// Attachment is the metadata row for one stored file.
type Attachment struct {
	ID          string    `json:"id"`
	TaskID      string    `json:"task_id"`
	Filename    string    `json:"filename"`
	ContentType string    `json:"content_type"`
	SizeBytes   int64     `json:"size_bytes"`
	StorageKey  string    `json:"storage_key"`
	CreatedAt   time.Time `json:"created_at"`
}

// Repo is the attachments repository backed by sqlc-generated queries. Every
// method takes orgID and joins through tasks (the generated SQL filters on
// t.org_id) so a caller can only see their own org's files.
type Repo struct {
	q *db.Queries
}

func NewRepo(pool *pgxpool.Pool) *Repo { return &Repo{q: db.New(pool)} }

func toAttachment(a db.Attachment) Attachment {
	return Attachment{
		ID:          a.ID.String(),
		TaskID:      a.TaskID.String(),
		Filename:    a.Filename,
		ContentType: a.ContentType,
		SizeBytes:   a.SizeBytes,
		StorageKey:  a.StorageKey,
		CreatedAt:   a.CreatedAt,
	}
}

// taskInOrg reports whether the task exists in the org. Used to gate writes so
// a caller can't attach a file to another tenant's task.
func (r *Repo) taskInOrg(ctx context.Context, oid, tid uuid.UUID) (bool, error) {
	ok, err := r.q.TaskInOrg(ctx, db.TaskInOrgParams{ID: tid, OrgID: oid})
	if err != nil {
		return false, fmt.Errorf("attachments.taskInOrg: %w", err)
	}
	return ok, nil
}

// Create inserts an attachment row after confirming the task is in the org.
func (r *Repo) Create(ctx context.Context, orgID, taskID, filename, contentType string, size int64, storageKey string) (Attachment, error) {
	tid, err := uuid.Parse(taskID)
	if err != nil {
		return Attachment{}, ErrNotFound // task not in org → don't leak its existence
	}
	oid, err := uuid.Parse(orgID)
	if err != nil {
		return Attachment{}, ErrNotFound
	}
	ok, err := r.taskInOrg(ctx, oid, tid)
	if err != nil {
		return Attachment{}, err
	}
	if !ok {
		return Attachment{}, ErrNotFound // task not in org → don't leak its existence
	}

	a, err := r.q.CreateAttachment(ctx, db.CreateAttachmentParams{
		TaskID:      tid,
		Filename:    filename,
		ContentType: contentType,
		SizeBytes:   size,
		StorageKey:  storageKey,
	})
	if err != nil {
		return Attachment{}, fmt.Errorf("attachments.Create: %w", err)
	}
	return toAttachment(a), nil
}

// ListByTask returns a task's attachments, scoped to the org via the join.
func (r *Repo) ListByTask(ctx context.Context, orgID, taskID string) ([]Attachment, error) {
	tid, err := uuid.Parse(taskID)
	if err != nil {
		return []Attachment{}, nil
	}
	oid, err := uuid.Parse(orgID)
	if err != nil {
		return []Attachment{}, nil
	}
	rows, err := r.q.ListAttachmentsByTask(ctx, db.ListAttachmentsByTaskParams{TaskID: tid, OrgID: oid})
	if err != nil {
		return nil, fmt.Errorf("attachments.ListByTask: %w", err)
	}
	out := make([]Attachment, 0, len(rows))
	for _, a := range rows {
		out = append(out, toAttachment(a))
	}
	return out, nil
}

// GetByID returns one attachment scoped to the org via the join.
func (r *Repo) GetByID(ctx context.Context, orgID, id string) (Attachment, error) {
	aid, err := uuid.Parse(id)
	if err != nil {
		return Attachment{}, ErrNotFound
	}
	oid, err := uuid.Parse(orgID)
	if err != nil {
		return Attachment{}, ErrNotFound
	}
	a, err := r.q.GetAttachmentByID(ctx, db.GetAttachmentByIDParams{ID: aid, OrgID: oid})
	if err != nil {
		if errors.Is(err, pgx.ErrNoRows) {
			return Attachment{}, ErrNotFound
		}
		return Attachment{}, fmt.Errorf("attachments.GetByID: %w", err)
	}
	return toAttachment(a), nil
}

// Service holds the attachment business rules.
type Service struct {
	repo *Repo
}

func NewService(repo *Repo) *Service { return &Service{repo: repo} }

// NewStorageKey builds a collision-resistant object key for a file. The shape
// org/<orgID>/task/<taskID>/<random>-<filename> keeps a tenant's files under a
// shared prefix (handy for lifecycle rules) while staying unguessable.
func NewStorageKey(orgID, taskID, filename string) string {
	var b [16]byte
	_, _ = rand.Read(b[:])
	return fmt.Sprintf("org/%s/task/%s/%s-%s", orgID, taskID, hex.EncodeToString(b[:]), path.Base(filename))
}

// Create records an attachment with a freshly generated storage key and returns
// the row (whose StorageKey the handler presigns an upload URL for).
func (s *Service) Create(ctx context.Context, orgID, taskID, filename, contentType string, size int64) (Attachment, error) {
	key := NewStorageKey(orgID, taskID, filename)
	return s.repo.Create(ctx, orgID, taskID, filename, contentType, size, key)
}

// List returns a task's attachments, org-scoped.
func (s *Service) List(ctx context.Context, orgID, taskID string) ([]Attachment, error) {
	return s.repo.ListByTask(ctx, orgID, taskID)
}

// Get returns one attachment, org-scoped.
func (s *Service) Get(ctx context.Context, orgID, id string) (Attachment, error) {
	return s.repo.GetByID(ctx, orgID, id)
}
