// Package orgs owns organizations and memberships — the multi-tenant core.
// A membership ties one user to one organization and carries their role; the
// role is a property of the user IN that org, never of the user alone. That
// shape is what makes "wrong person, wrong room" bugs impossible to write.
//
// Course mapping: Chapter 7 — multi-tenancy; Chapter 17 — RBAC (owner > admin
// > member); Chapter 21 — service layer (CreateOrg runs in a transaction).
//
// Course mapping: Chapter 8 — the orgs/memberships queries are now generated by
// sqlc (internal/db). The CreateOrg + owner-membership transaction stays atomic
// via the sqlc Queries.WithTx pattern over a pgx transaction. UUIDs cross the
// package boundary as text (the domain structs expose string IDs), so each
// method parses inbound IDs and stringifies the generated uuid.UUID columns.
package orgs

import (
	"context"
	"errors"
	"fmt"
	"strings"
	"time"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5"
	"github.com/jackc/pgx/v5/pgxpool"

	"beacon/internal/cache"
	"beacon/internal/db"
	"beacon/internal/pgerr"
)

// Roles, highest authority first. RoleRank lets requireRole compare them.
const (
	RoleOwner  = "owner"
	RoleAdmin  = "admin"
	RoleMember = "member"
)

// RoleRank maps a role to a comparable rank; higher means more authority.
// Unknown roles rank 0.
func RoleRank(role string) int {
	switch role {
	case RoleOwner:
		return 3
	case RoleAdmin:
		return 2
	case RoleMember:
		return 1
	default:
		return 0
	}
}

// Sentinel errors.
var (
	ErrNotMember     = errors.New("not a member of this organization")
	ErrForbidden     = errors.New("forbidden")
	ErrUserNotFound  = errors.New("user not found")
	ErrAlreadyMember = errors.New("user is already a member")
	ErrNotFound      = errors.New("organization not found")
)

// Org is an organization.
type Org struct {
	ID        string    `json:"id"`
	Name      string    `json:"name"`
	Slug      string    `json:"slug"`
	CreatedAt time.Time `json:"created_at"`
}

// Membership ties a user to an org with a role.
type Membership struct {
	ID        string    `json:"id"`
	UserID    string    `json:"user_id"`
	OrgID     string    `json:"org_id"`
	Role      string    `json:"role" enum:"owner,admin,member"`
	CreatedAt time.Time `json:"created_at"`
}

// OrgWithRole is an org plus the caller's role in it (for ListForUser).
type OrgWithRole struct {
	Org
	Role string `json:"role" enum:"owner,admin,member"`
}

// Member is a membership joined with the user's identity (for ListMembers).
type Member struct {
	UserID string `json:"user_id"`
	Email  string `json:"email"`
	Name   string `json:"name"`
	Role   string `json:"role" enum:"owner,admin,member"`
}

// Repo is the orgs/memberships repository backed by sqlc-generated queries.
type Repo struct {
	q *db.Queries
}

func NewRepo(pool *pgxpool.Pool) *Repo { return &Repo{q: db.New(pool)} }

// createOrg inserts an organization using the given Queries (pool or tx-bound).
func (r *Repo) createOrg(ctx context.Context, q *db.Queries, name, slug string) (Org, error) {
	row, err := q.CreateOrg(ctx, db.CreateOrgParams{Name: name, Slug: slug})
	if err != nil {
		if pgerr.IsUniqueViolation(err) {
			return Org{}, ErrAlreadyMember // slug collision is rare; treated as conflict
		}
		return Org{}, fmt.Errorf("orgs.createOrg: %w", err)
	}
	return Org{
		ID:        row.ID.String(),
		Name:      row.Name,
		Slug:      row.Slug,
		CreatedAt: row.CreatedAt,
	}, nil
}

// CreateOrg inserts an organization (standalone, no membership).
func (r *Repo) CreateOrg(ctx context.Context, name, slug string) (Org, error) {
	return r.createOrg(ctx, r.q, name, slug)
}

// addMembership inserts a membership using the given Queries (pool or tx-bound).
func (r *Repo) addMembership(ctx context.Context, q *db.Queries, userID, orgID, role string) (Membership, error) {
	uid, err := uuid.Parse(userID)
	if err != nil {
		return Membership{}, fmt.Errorf("orgs.addMembership: parse user id: %w", err)
	}
	oid, err := uuid.Parse(orgID)
	if err != nil {
		return Membership{}, fmt.Errorf("orgs.addMembership: parse org id: %w", err)
	}
	m, err := q.AddMembership(ctx, db.AddMembershipParams{UserID: uid, OrgID: oid, Role: role})
	if err != nil {
		if pgerr.IsUniqueViolation(err) {
			return Membership{}, ErrAlreadyMember
		}
		return Membership{}, fmt.Errorf("orgs.addMembership: %w", err)
	}
	return Membership{
		ID:        m.ID.String(),
		UserID:    m.UserID.String(),
		OrgID:     m.OrgID.String(),
		Role:      m.Role,
		CreatedAt: m.CreatedAt,
	}, nil
}

// AddMembership inserts a membership (standalone).
func (r *Repo) AddMembership(ctx context.Context, userID, orgID, role string) (Membership, error) {
	return r.addMembership(ctx, r.q, userID, orgID, role)
}

// GetMembership returns the caller's membership in an org, or ErrNotMember.
func (r *Repo) GetMembership(ctx context.Context, userID, orgID string) (Membership, error) {
	uid, err := uuid.Parse(userID)
	if err != nil {
		return Membership{}, ErrNotMember
	}
	oid, err := uuid.Parse(orgID)
	if err != nil {
		return Membership{}, ErrNotMember
	}
	m, err := r.q.GetMembership(ctx, db.GetMembershipParams{UserID: uid, OrgID: oid})
	if err != nil {
		if errors.Is(err, pgx.ErrNoRows) {
			return Membership{}, ErrNotMember
		}
		return Membership{}, fmt.Errorf("orgs.GetMembership: %w", err)
	}
	return Membership{
		ID:        m.ID.String(),
		UserID:    m.UserID.String(),
		OrgID:     m.OrgID.String(),
		Role:      m.Role,
		CreatedAt: m.CreatedAt,
	}, nil
}

// ListOrgsForUser returns every org the user belongs to, with their role.
func (r *Repo) ListOrgsForUser(ctx context.Context, userID string) ([]OrgWithRole, error) {
	uid, err := uuid.Parse(userID)
	if err != nil {
		return []OrgWithRole{}, nil // a malformed id belongs to no orgs
	}
	rows, err := r.q.ListOrgsForUser(ctx, uid)
	if err != nil {
		return nil, fmt.Errorf("orgs.ListOrgsForUser: %w", err)
	}
	out := make([]OrgWithRole, 0, len(rows))
	for _, row := range rows {
		out = append(out, OrgWithRole{
			Org: Org{
				ID:        row.ID.String(),
				Name:      row.Name,
				Slug:      row.Slug,
				CreatedAt: row.CreatedAt,
			},
			Role: row.Role,
		})
	}
	return out, nil
}

// ListMembers returns every member of an org joined with their identity.
func (r *Repo) ListMembers(ctx context.Context, orgID string) ([]Member, error) {
	oid, err := uuid.Parse(orgID)
	if err != nil {
		return []Member{}, nil
	}
	rows, err := r.q.ListMembers(ctx, oid)
	if err != nil {
		return nil, fmt.Errorf("orgs.ListMembers: %w", err)
	}
	out := make([]Member, 0, len(rows))
	for _, row := range rows {
		out = append(out, Member{
			UserID: row.ID.String(),
			Email:  row.Email,
			Name:   row.Name,
			Role:   row.Role,
		})
	}
	return out, nil
}

// findUserIDByEmail resolves an email to a user ID (for AddMember).
func (r *Repo) findUserIDByEmail(ctx context.Context, q *db.Queries, email string) (string, error) {
	id, err := q.FindUserIDByEmail(ctx, email)
	if err != nil {
		if errors.Is(err, pgx.ErrNoRows) {
			return "", ErrUserNotFound
		}
		return "", fmt.Errorf("orgs.findUserIDByEmail: %w", err)
	}
	return id.String(), nil
}

// Service holds the org business rules.
type Service struct {
	repo *Repo
	pool *pgxpool.Pool

	// Ch 28 — the membership cache. This is the hottest read in the whole API:
	// requireOrg looks a membership up on every single org-scoped request, and
	// the answer is a tiny row that changes about as often as someone joins a
	// team. Exactly the shape the chapter says to cache. Nil = uncached.
	memberships *cache.CachedReader[Membership]
}

func NewService(repo *Repo, pool *pgxpool.Pool) *Service {
	return &Service{repo: repo, pool: pool}
}

// WithCache attaches the Chapter 28 read-through cache. Called from the wiring
// step in NewServer; without it the service just reads Postgres every time.
func (s *Service) WithCache(c *cache.CachedReader[Membership]) *Service {
	s.memberships = c
	return s
}

// membershipKey scopes every cache entry by org AND user. The chapter's rule:
// put the tenant in the key, so the worst bug a typo can cause is a miss rather
// than one customer reading another customer's data.
func membershipKey(userID, orgID string) string {
	return "membership:" + orgID + ":" + userID
}

// CreateOrg creates an organization and the owner's membership in a single
// transaction — either both land or neither does.
func (s *Service) CreateOrg(ctx context.Context, ownerID, name string) (Org, error) {
	tx, err := s.pool.Begin(ctx)
	if err != nil {
		return Org{}, fmt.Errorf("orgs.CreateOrg: begin: %w", err)
	}
	defer tx.Rollback(ctx) //nolint:errcheck // no-op after a successful commit

	// Bind a sqlc Queries to this transaction so both writes commit together.
	qtx := s.repo.q.WithTx(tx)
	org, err := s.repo.createOrg(ctx, qtx, name, slugify(name))
	if err != nil {
		return Org{}, err
	}
	if _, err := s.repo.addMembership(ctx, qtx, ownerID, org.ID, RoleOwner); err != nil {
		return Org{}, err
	}
	if err := tx.Commit(ctx); err != nil {
		return Org{}, fmt.Errorf("orgs.CreateOrg: commit: %w", err)
	}
	return org, nil
}

// ListForUser returns every org the caller belongs to, with their role.
func (s *Service) ListForUser(ctx context.Context, userID string) ([]OrgWithRole, error) {
	return s.repo.ListOrgsForUser(ctx, userID)
}

// AddMember adds a user (looked up by email) to an org with the given role.
// Only owners and admins may add members (RBAC), and only an owner may grant
// the owner role.
func (s *Service) AddMember(ctx context.Context, orgID, actorRole, email, role string) (Membership, error) {
	if RoleRank(actorRole) < RoleRank(RoleAdmin) {
		return Membership{}, ErrForbidden
	}
	if role != RoleOwner && role != RoleAdmin && role != RoleMember {
		return Membership{}, fmt.Errorf("orgs.AddMember: %w: unknown role %q", ErrForbidden, role)
	}
	// Only an owner may mint another owner.
	if role == RoleOwner && actorRole != RoleOwner {
		return Membership{}, ErrForbidden
	}

	userID, err := s.repo.findUserIDByEmail(ctx, s.repo.q, email)
	if err != nil {
		return Membership{}, err
	}
	m, err := s.repo.AddMembership(ctx, userID, orgID, role)
	if err != nil {
		return Membership{}, err
	}

	// Ch 28 — invalidate AFTER the write commits, never before. Best effort: a
	// failed delete means one stale read for at most the TTL, which is a much
	// smaller problem than a failed request.
	if s.memberships != nil {
		if err := s.memberships.Del(ctx, membershipKey(userID, orgID)); err != nil {
			// Nothing to do about it here; the TTL is the backstop.
			_ = err
		}
	}
	return m, nil
}

// Members lists an org's members.
func (s *Service) Members(ctx context.Context, orgID string) ([]Member, error) {
	return s.repo.ListMembers(ctx, orgID)
}

// GetMembership returns the caller's membership (used by middleware).
//
// Ch 28: a read-through cache sits in front of it. Miss walks in-process LRU →
// Redis → Postgres, and singleflight means a hot key expiring under load runs
// the query once, not once per waiting request.
//
// Note what is NOT cached: ErrNotMember. Caching a negative here would mean a
// user added to an org keeps getting 403 for the whole TTL, and "I was invited
// and it still says no" is a much worse bug than one extra query.
func (s *Service) GetMembership(ctx context.Context, userID, orgID string) (Membership, error) {
	if s.memberships == nil {
		return s.repo.GetMembership(ctx, userID, orgID)
	}
	return s.memberships.Get(ctx, membershipKey(userID, orgID),
		func(ctx context.Context) (Membership, error) {
			return s.repo.GetMembership(ctx, userID, orgID)
		})
}

// slugify turns a name into a URL-safe, unique-ish slug. We append a short
// timestamp suffix so two orgs with the same name don't collide on the slug's
// unique index.
func slugify(name string) string {
	var b strings.Builder
	for _, r := range strings.ToLower(name) {
		switch {
		case r >= 'a' && r <= 'z', r >= '0' && r <= '9':
			b.WriteRune(r)
		case r == ' ' || r == '-' || r == '_':
			b.WriteByte('-')
		}
	}
	base := strings.Trim(b.String(), "-")
	if base == "" {
		base = "org"
	}
	return fmt.Sprintf("%s-%d", base, time.Now().UnixNano()%1_000_000)
}
