// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: attachments.sql

package db

import (
	"context"

	"github.com/google/uuid"
)

const createAttachment = `-- name: CreateAttachment :one
INSERT INTO attachments (task_id, filename, content_type, size_bytes, storage_key)
VALUES ($1, $2, $3, $4, $5)
RETURNING id, task_id, filename, content_type, size_bytes, storage_key, created_at
`

type CreateAttachmentParams struct {
	TaskID      uuid.UUID `json:"task_id"`
	Filename    string    `json:"filename"`
	ContentType string    `json:"content_type"`
	SizeBytes   int64     `json:"size_bytes"`
	StorageKey  string    `json:"storage_key"`
}

func (q *Queries) CreateAttachment(ctx context.Context, arg CreateAttachmentParams) (Attachment, error) {
	row := q.db.QueryRow(ctx, createAttachment,
		arg.TaskID,
		arg.Filename,
		arg.ContentType,
		arg.SizeBytes,
		arg.StorageKey,
	)
	var i Attachment
	err := row.Scan(
		&i.ID,
		&i.TaskID,
		&i.Filename,
		&i.ContentType,
		&i.SizeBytes,
		&i.StorageKey,
		&i.CreatedAt,
	)
	return i, err
}

const getAttachmentByID = `-- name: GetAttachmentByID :one
SELECT a.id, a.task_id, a.filename, a.content_type, a.size_bytes, a.storage_key, a.created_at
FROM attachments a
JOIN tasks t ON t.id = a.task_id
WHERE a.id = $1 AND t.org_id = $2 AND t.deleted_at IS NULL
`

type GetAttachmentByIDParams struct {
	ID    uuid.UUID `json:"id"`
	OrgID uuid.UUID `json:"org_id"`
}

func (q *Queries) GetAttachmentByID(ctx context.Context, arg GetAttachmentByIDParams) (Attachment, error) {
	row := q.db.QueryRow(ctx, getAttachmentByID, arg.ID, arg.OrgID)
	var i Attachment
	err := row.Scan(
		&i.ID,
		&i.TaskID,
		&i.Filename,
		&i.ContentType,
		&i.SizeBytes,
		&i.StorageKey,
		&i.CreatedAt,
	)
	return i, err
}

const listAttachmentsByTask = `-- name: ListAttachmentsByTask :many
SELECT a.id, a.task_id, a.filename, a.content_type, a.size_bytes, a.storage_key, a.created_at
FROM attachments a
JOIN tasks t ON t.id = a.task_id
WHERE a.task_id = $1 AND t.org_id = $2 AND t.deleted_at IS NULL
ORDER BY a.created_at DESC
`

type ListAttachmentsByTaskParams struct {
	TaskID uuid.UUID `json:"task_id"`
	OrgID  uuid.UUID `json:"org_id"`
}

func (q *Queries) ListAttachmentsByTask(ctx context.Context, arg ListAttachmentsByTaskParams) ([]Attachment, error) {
	rows, err := q.db.Query(ctx, listAttachmentsByTask, arg.TaskID, arg.OrgID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Attachment
	for rows.Next() {
		var i Attachment
		if err := rows.Scan(
			&i.ID,
			&i.TaskID,
			&i.Filename,
			&i.ContentType,
			&i.SizeBytes,
			&i.StorageKey,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const taskInOrg = `-- name: TaskInOrg :one

SELECT EXISTS (SELECT 1 FROM tasks WHERE id = $1 AND org_id = $2 AND deleted_at IS NULL)
`

type TaskInOrgParams struct {
	ID    uuid.UUID `json:"id"`
	OrgID uuid.UUID `json:"org_id"`
}

// Attachments — no org_id of their own; scoped by joining through tasks.org_id.
// (Chapter 8 / sqlc)
//
// Chapter 10: attachments get no deleted_at of their own, for the same reason
// comments don't (see the migration's header) — their visibility, and now
// whether a task can receive a new one, follows tasks.deleted_at instead.
func (q *Queries) TaskInOrg(ctx context.Context, arg TaskInOrgParams) (bool, error) {
	row := q.db.QueryRow(ctx, taskInOrg, arg.ID, arg.OrgID)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}
