// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: audit.sql

package db

import (
	"context"

	"github.com/google/uuid"
)

const insertAuditEntry = `-- name: InsertAuditEntry :exec

INSERT INTO audit_log (org_id, actor_id, action, resource_type, resource_id)
VALUES ($1, $2, $3, $4, $5)
`

type InsertAuditEntryParams struct {
	OrgID        uuid.UUID `json:"org_id"`
	ActorID      uuid.UUID `json:"actor_id"`
	Action       string    `json:"action"`
	ResourceType string    `json:"resource_type"`
	ResourceID   uuid.UUID `json:"resource_id"`
}

// Audit log — one row per mutation an org needs to be able to answer "who,
// and when" about. (Chapter 10 / sqlc)
func (q *Queries) InsertAuditEntry(ctx context.Context, arg InsertAuditEntryParams) error {
	_, err := q.db.Exec(ctx, insertAuditEntry,
		arg.OrgID,
		arg.ActorID,
		arg.Action,
		arg.ResourceType,
		arg.ResourceID,
	)
	return err
}

const listAuditLog = `-- name: ListAuditLog :many
SELECT id, org_id, actor_id, action, resource_type, resource_id, created_at
FROM audit_log
WHERE org_id = $1
ORDER BY created_at DESC, id DESC
LIMIT $2 OFFSET $3
`

type ListAuditLogParams struct {
	OrgID  uuid.UUID `json:"org_id"`
	Limit  int32     `json:"limit"`
	Offset int32     `json:"offset"`
}

func (q *Queries) ListAuditLog(ctx context.Context, arg ListAuditLogParams) ([]AuditLog, error) {
	rows, err := q.db.Query(ctx, listAuditLog, arg.OrgID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []AuditLog
	for rows.Next() {
		var i AuditLog
		if err := rows.Scan(
			&i.ID,
			&i.OrgID,
			&i.ActorID,
			&i.Action,
			&i.ResourceType,
			&i.ResourceID,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
