// Package db is generated by sqlc. Do not hand-edit anything in it except
// this file.
//
// The schema in migrations/ is the source of truth. sqlc reads it to learn
// every column's type, type-checks the queries in queries/*.sql against it,
// and emits the Go functions and row structs here. A query that references a
// column that does not exist fails at `sqlc generate`, not in production.
//
// # The loop
//
//	edit migrations/ or internal/db/queries/*.sql
//	make -C api sqlc          # regenerate
//	commit both the SQL and the generated Go
//
// # What is in here and what is not
//
// Every CRUD repository is generated: users, orgs, projects, tasks,
// attachments, webhooks, idempotency keys, search, flags, experiments. Each
// generated query for a tenant-owned table carries its own `WHERE org_id =
// $1` — the tenant boundary is in the SQL, not in a wrapper somebody can
// forget to call.
//
// The jobs queue is NOT generated. Its worker claims rows with FOR UPDATE
// SKIP LOCKED inside a transaction, which sqlc expresses awkwardly, so
// internal/jobs stays hand-written pgx.
//
// # Two layout choices worth knowing
//
// The course threads one .sql file per domain into that domain's own package.
// This points every query file at a single internal/db package instead, so
// there is one importable Queries type and one place to look.
//
// UUIDs are overridden to google/uuid.UUID and timestamps to time.Time rather
// than leaving them as pgtype values (see sqlc.yaml). The domain packages
// expose string IDs, so each repository method parses inbound IDs and
// stringifies outbound ones at its own edge.
//
// Course mapping: Chapter 8 — generated queries.
package db
