// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: idempotency.sql

package db

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const claimIdempotencyKey = `-- name: ClaimIdempotencyKey :one

INSERT INTO idempotency_keys (user_id, key, request_hash, method, path)
VALUES ($1, $2, $3, $4, $5)
ON CONFLICT (user_id, key) DO UPDATE SET key = EXCLUDED.key
RETURNING
    request_hash,
    method,
    path,
    response_status,
    response_body,
    completed_at,
    (xmax = 0) AS claimed
`

type ClaimIdempotencyKeyParams struct {
	UserID      uuid.UUID `json:"user_id"`
	Key         string    `json:"key"`
	RequestHash []byte    `json:"request_hash"`
	Method      string    `json:"method"`
	Path        string    `json:"path"`
}

type ClaimIdempotencyKeyRow struct {
	RequestHash    []byte     `json:"request_hash"`
	Method         string     `json:"method"`
	Path           string     `json:"path"`
	ResponseStatus *int32     `json:"response_status"`
	ResponseBody   []byte     `json:"response_body"`
	CompletedAt    *time.Time `json:"completed_at"`
	Claimed        bool       `json:"claimed"`
}

// Chapter 14 — idempotency. Two queries, and the first one is the whole trick.
//
// [verbatim ch14] except for the file's location: the chapter puts this at
// internal/http/idempotency_queries.sql behind a second sqlc target. This repo
// generates every query into one internal/db package (see sqlc.yaml), so it
// lives here with the rest. The SQL is unchanged.
// Atomic: insert the row if no key exists for this (user_id, key), or
// return the existing row if one does. The "claimed" boolean tells the
// caller which happened.
func (q *Queries) ClaimIdempotencyKey(ctx context.Context, arg ClaimIdempotencyKeyParams) (ClaimIdempotencyKeyRow, error) {
	row := q.db.QueryRow(ctx, claimIdempotencyKey,
		arg.UserID,
		arg.Key,
		arg.RequestHash,
		arg.Method,
		arg.Path,
	)
	var i ClaimIdempotencyKeyRow
	err := row.Scan(
		&i.RequestHash,
		&i.Method,
		&i.Path,
		&i.ResponseStatus,
		&i.ResponseBody,
		&i.CompletedAt,
		&i.Claimed,
	)
	return i, err
}

const completeIdempotencyKey = `-- name: CompleteIdempotencyKey :exec
UPDATE idempotency_keys
SET response_status = $3, response_body = $4, completed_at = now()
WHERE user_id = $1 AND key = $2 AND completed_at IS NULL
`

type CompleteIdempotencyKeyParams struct {
	UserID         uuid.UUID `json:"user_id"`
	Key            string    `json:"key"`
	ResponseStatus *int32    `json:"response_status"`
	ResponseBody   []byte    `json:"response_body"`
}

func (q *Queries) CompleteIdempotencyKey(ctx context.Context, arg CompleteIdempotencyKeyParams) error {
	_, err := q.db.Exec(ctx, completeIdempotencyKey,
		arg.UserID,
		arg.Key,
		arg.ResponseStatus,
		arg.ResponseBody,
	)
	return err
}

const sweepIdempotencyKeys = `-- name: SweepIdempotencyKeys :execrows
DELETE FROM idempotency_keys WHERE created_at < now() - interval '24 hours'
`

// The daily cron entry: 24 hours is long enough for any sane retry and short
// enough that the table stays small (Chapter 14, the "housekeeping" section).
func (q *Queries) SweepIdempotencyKeys(ctx context.Context) (int64, error) {
	result, err := q.db.Exec(ctx, sweepIdempotencyKeys)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}
