// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package db

import (
	"time"

	"github.com/google/uuid"
)

type Attachment struct {
	ID          uuid.UUID `json:"id"`
	TaskID      uuid.UUID `json:"task_id"`
	Filename    string    `json:"filename"`
	ContentType string    `json:"content_type"`
	SizeBytes   int64     `json:"size_bytes"`
	StorageKey  string    `json:"storage_key"`
	CreatedAt   time.Time `json:"created_at"`
}

type AuditLog struct {
	ID           uuid.UUID `json:"id"`
	OrgID        uuid.UUID `json:"org_id"`
	ActorID      uuid.UUID `json:"actor_id"`
	Action       string    `json:"action"`
	ResourceType string    `json:"resource_type"`
	ResourceID   uuid.UUID `json:"resource_id"`
	CreatedAt    time.Time `json:"created_at"`
}

type Comment struct {
	ID        uuid.UUID `json:"id"`
	TaskID    uuid.UUID `json:"task_id"`
	AuthorID  uuid.UUID `json:"author_id"`
	Body      string    `json:"body"`
	CreatedAt time.Time `json:"created_at"`
}

type Experiment struct {
	Key         string     `json:"key"`
	Description string     `json:"description"`
	Status      string     `json:"status"`
	Variants    []byte     `json:"variants"`
	StartedAt   *time.Time `json:"started_at"`
	StoppedAt   *time.Time `json:"stopped_at"`
	CreatedAt   time.Time  `json:"created_at"`
}

type ExperimentAssignment struct {
	ExperimentKey string    `json:"experiment_key"`
	UserID        uuid.UUID `json:"user_id"`
	Variant       string    `json:"variant"`
	AssignedAt    time.Time `json:"assigned_at"`
}

type FeatureFlag struct {
	Name         string    `json:"name"`
	Description  string    `json:"description"`
	DefaultValue bool      `json:"default_value"`
	CreatedAt    time.Time `json:"created_at"`
	UpdatedAt    time.Time `json:"updated_at"`
}

type FeatureFlagOverride struct {
	FlagName  string     `json:"flag_name"`
	OrgID     *uuid.UUID `json:"org_id"`
	UserID    *uuid.UUID `json:"user_id"`
	Value     bool       `json:"value"`
	CreatedAt time.Time  `json:"created_at"`
}

type IdempotencyKey struct {
	Key            string     `json:"key"`
	UserID         uuid.UUID  `json:"user_id"`
	RequestHash    []byte     `json:"request_hash"`
	Method         string     `json:"method"`
	Path           string     `json:"path"`
	ResponseStatus *int32     `json:"response_status"`
	ResponseBody   []byte     `json:"response_body"`
	CreatedAt      time.Time  `json:"created_at"`
	CompletedAt    *time.Time `json:"completed_at"`
}

type Job struct {
	ID           uuid.UUID `json:"id"`
	Kind         string    `json:"kind"`
	Payload      []byte    `json:"payload"`
	RunAt        time.Time `json:"run_at"`
	Attempts     int32     `json:"attempts"`
	MaxAttempts  int32     `json:"max_attempts"`
	Status       string    `json:"status"`
	LastError    string    `json:"last_error"`
	CreatedAt    time.Time `json:"created_at"`
	TraceContext []byte    `json:"trace_context"`
}

type Membership struct {
	ID        uuid.UUID `json:"id"`
	UserID    uuid.UUID `json:"user_id"`
	OrgID     uuid.UUID `json:"org_id"`
	Role      string    `json:"role"`
	CreatedAt time.Time `json:"created_at"`
}

type Organization struct {
	ID            uuid.UUID `json:"id"`
	Name          string    `json:"name"`
	Slug          string    `json:"slug"`
	CreatedAt     time.Time `json:"created_at"`
	UpdatedAt     time.Time `json:"updated_at"`
	DefaultLocale string    `json:"default_locale"`
}

type Project struct {
	ID        uuid.UUID  `json:"id"`
	OrgID     uuid.UUID  `json:"org_id"`
	Name      string     `json:"name"`
	CreatedAt time.Time  `json:"created_at"`
	UpdatedAt time.Time  `json:"updated_at"`
	DeletedAt *time.Time `json:"deleted_at"`
}

type SearchIndex struct {
	ID             uuid.UUID   `json:"id"`
	OrganizationID uuid.UUID   `json:"organization_id"`
	EntityKind     string      `json:"entity_kind"`
	EntityID       uuid.UUID   `json:"entity_id"`
	Title          string      `json:"title"`
	Body           string      `json:"body"`
	SearchVector   interface{} `json:"search_vector"`
	UpdatedAt      time.Time   `json:"updated_at"`
}

type Task struct {
	ID        uuid.UUID  `json:"id"`
	OrgID     uuid.UUID  `json:"org_id"`
	ProjectID uuid.UUID  `json:"project_id"`
	Title     string     `json:"title"`
	Status    string     `json:"status"`
	Position  float64    `json:"position"`
	CreatedAt time.Time  `json:"created_at"`
	UpdatedAt time.Time  `json:"updated_at"`
	DeletedAt *time.Time `json:"deleted_at"`
}

type User struct {
	ID           uuid.UUID `json:"id"`
	Email        string    `json:"email"`
	PasswordHash string    `json:"password_hash"`
	Name         string    `json:"name"`
	CreatedAt    time.Time `json:"created_at"`
	UpdatedAt    time.Time `json:"updated_at"`
	Locale       string    `json:"locale"`
	Timezone     string    `json:"timezone"`
}

type Webhook struct {
	ID        uuid.UUID  `json:"id"`
	OrgID     uuid.UUID  `json:"org_id"`
	Url       string     `json:"url"`
	Secret    string     `json:"secret"`
	Events    []string   `json:"events"`
	Active    bool       `json:"active"`
	CreatedAt time.Time  `json:"created_at"`
	DeletedAt *time.Time `json:"deleted_at"`
}

type WebhookDelivery struct {
	ID          uuid.UUID  `json:"id"`
	WebhookID   uuid.UUID  `json:"webhook_id"`
	Event       string     `json:"event"`
	Payload     []byte     `json:"payload"`
	Status      string     `json:"status"`
	Attempts    int32      `json:"attempts"`
	LastError   string     `json:"last_error"`
	CreatedAt   time.Time  `json:"created_at"`
	DeliveredAt *time.Time `json:"delivered_at"`
}
