// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: orgs.sql

package db

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const addMembership = `-- name: AddMembership :one
INSERT INTO memberships (user_id, org_id, role)
VALUES ($1, $2, $3)
RETURNING id, user_id, org_id, role, created_at
`

type AddMembershipParams struct {
	UserID uuid.UUID `json:"user_id"`
	OrgID  uuid.UUID `json:"org_id"`
	Role   string    `json:"role"`
}

func (q *Queries) AddMembership(ctx context.Context, arg AddMembershipParams) (Membership, error) {
	row := q.db.QueryRow(ctx, addMembership, arg.UserID, arg.OrgID, arg.Role)
	var i Membership
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.OrgID,
		&i.Role,
		&i.CreatedAt,
	)
	return i, err
}

const createOrg = `-- name: CreateOrg :one

INSERT INTO organizations (name, slug)
VALUES ($1, $2)
RETURNING id, name, slug, created_at
`

type CreateOrgParams struct {
	Name string `json:"name"`
	Slug string `json:"slug"`
}

type CreateOrgRow struct {
	ID        uuid.UUID `json:"id"`
	Name      string    `json:"name"`
	Slug      string    `json:"slug"`
	CreatedAt time.Time `json:"created_at"`
}

// Organizations + memberships — the multi-tenant core. (Chapter 8 / sqlc)
func (q *Queries) CreateOrg(ctx context.Context, arg CreateOrgParams) (CreateOrgRow, error) {
	row := q.db.QueryRow(ctx, createOrg, arg.Name, arg.Slug)
	var i CreateOrgRow
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Slug,
		&i.CreatedAt,
	)
	return i, err
}

const findUserIDByEmail = `-- name: FindUserIDByEmail :one
SELECT id
FROM users
WHERE lower(email) = lower($1)
`

func (q *Queries) FindUserIDByEmail(ctx context.Context, lower string) (uuid.UUID, error) {
	row := q.db.QueryRow(ctx, findUserIDByEmail, lower)
	var id uuid.UUID
	err := row.Scan(&id)
	return id, err
}

const getMembership = `-- name: GetMembership :one
SELECT id, user_id, org_id, role, created_at
FROM memberships
WHERE user_id = $1 AND org_id = $2
`

type GetMembershipParams struct {
	UserID uuid.UUID `json:"user_id"`
	OrgID  uuid.UUID `json:"org_id"`
}

func (q *Queries) GetMembership(ctx context.Context, arg GetMembershipParams) (Membership, error) {
	row := q.db.QueryRow(ctx, getMembership, arg.UserID, arg.OrgID)
	var i Membership
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.OrgID,
		&i.Role,
		&i.CreatedAt,
	)
	return i, err
}

const listMembers = `-- name: ListMembers :many
SELECT u.id, u.email, u.name, m.role
FROM memberships m
JOIN users u ON u.id = m.user_id
WHERE m.org_id = $1
ORDER BY m.created_at ASC
`

type ListMembersRow struct {
	ID    uuid.UUID `json:"id"`
	Email string    `json:"email"`
	Name  string    `json:"name"`
	Role  string    `json:"role"`
}

func (q *Queries) ListMembers(ctx context.Context, orgID uuid.UUID) ([]ListMembersRow, error) {
	rows, err := q.db.Query(ctx, listMembers, orgID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListMembersRow
	for rows.Next() {
		var i ListMembersRow
		if err := rows.Scan(
			&i.ID,
			&i.Email,
			&i.Name,
			&i.Role,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listOrgsForUser = `-- name: ListOrgsForUser :many
SELECT o.id, o.name, o.slug, o.created_at, m.role
FROM organizations o
JOIN memberships m ON m.org_id = o.id
WHERE m.user_id = $1
ORDER BY o.created_at DESC
`

type ListOrgsForUserRow struct {
	ID        uuid.UUID `json:"id"`
	Name      string    `json:"name"`
	Slug      string    `json:"slug"`
	CreatedAt time.Time `json:"created_at"`
	Role      string    `json:"role"`
}

func (q *Queries) ListOrgsForUser(ctx context.Context, userID uuid.UUID) ([]ListOrgsForUserRow, error) {
	rows, err := q.db.Query(ctx, listOrgsForUser, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListOrgsForUserRow
	for rows.Next() {
		var i ListOrgsForUserRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Slug,
			&i.CreatedAt,
			&i.Role,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
