// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: projects.sql

package db

import (
	"context"

	"github.com/google/uuid"
)

const createProject = `-- name: CreateProject :one

INSERT INTO projects (org_id, name)
VALUES ($1, $2)
RETURNING id, org_id, name, created_at, updated_at, deleted_at
`

type CreateProjectParams struct {
	OrgID uuid.UUID `json:"org_id"`
	Name  string    `json:"name"`
}

// Projects — every query scoped by org_id (the tenant boundary). (Chapter 8 / sqlc)
//
// Chapter 10: delete is soft. Every read below excludes deleted_at IS NOT
// NULL rows; the delete itself is SoftDeleteProject, an UPDATE, not a DELETE.
//
// deleted_at is selected/returned everywhere below even though every one of
// these queries already guarantees it is NULL (that is what "AND deleted_at
// IS NULL" means) — leaving it out would make sqlc's column list a strict
// subset of the projects table's, which stops it treating the result as a
// Project and gives every query its own near-identical Row type instead. The
// Go field this produces is real but always nil; internal/projects tags it
// `json:"-"` so it never reaches the API despite existing in Go.
func (q *Queries) CreateProject(ctx context.Context, arg CreateProjectParams) (Project, error) {
	row := q.db.QueryRow(ctx, createProject, arg.OrgID, arg.Name)
	var i Project
	err := row.Scan(
		&i.ID,
		&i.OrgID,
		&i.Name,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const getProjectByID = `-- name: GetProjectByID :one
SELECT id, org_id, name, created_at, updated_at, deleted_at
FROM projects
WHERE id = $1 AND org_id = $2 AND deleted_at IS NULL
`

type GetProjectByIDParams struct {
	ID    uuid.UUID `json:"id"`
	OrgID uuid.UUID `json:"org_id"`
}

func (q *Queries) GetProjectByID(ctx context.Context, arg GetProjectByIDParams) (Project, error) {
	row := q.db.QueryRow(ctx, getProjectByID, arg.ID, arg.OrgID)
	var i Project
	err := row.Scan(
		&i.ID,
		&i.OrgID,
		&i.Name,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const listProjectsByOrg = `-- name: ListProjectsByOrg :many
SELECT id, org_id, name, created_at, updated_at, deleted_at
FROM projects
WHERE org_id = $1 AND deleted_at IS NULL
ORDER BY created_at DESC, id DESC
LIMIT $2 OFFSET $3
`

type ListProjectsByOrgParams struct {
	OrgID  uuid.UUID `json:"org_id"`
	Limit  int32     `json:"limit"`
	Offset int32     `json:"offset"`
}

func (q *Queries) ListProjectsByOrg(ctx context.Context, arg ListProjectsByOrgParams) ([]Project, error) {
	rows, err := q.db.Query(ctx, listProjectsByOrg, arg.OrgID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Project
	for rows.Next() {
		var i Project
		if err := rows.Scan(
			&i.ID,
			&i.OrgID,
			&i.Name,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const softDeleteProject = `-- name: SoftDeleteProject :execrows
UPDATE projects SET deleted_at = now()
WHERE id = $1 AND org_id = $2 AND deleted_at IS NULL
`

type SoftDeleteProjectParams struct {
	ID    uuid.UUID `json:"id"`
	OrgID uuid.UUID `json:"org_id"`
}

func (q *Queries) SoftDeleteProject(ctx context.Context, arg SoftDeleteProjectParams) (int64, error) {
	result, err := q.db.Exec(ctx, softDeleteProject, arg.ID, arg.OrgID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const updateProject = `-- name: UpdateProject :one
UPDATE projects SET name = $3, updated_at = now()
WHERE id = $1 AND org_id = $2 AND deleted_at IS NULL
RETURNING id, org_id, name, created_at, updated_at, deleted_at
`

type UpdateProjectParams struct {
	ID    uuid.UUID `json:"id"`
	OrgID uuid.UUID `json:"org_id"`
	Name  string    `json:"name"`
}

func (q *Queries) UpdateProject(ctx context.Context, arg UpdateProjectParams) (Project, error) {
	row := q.db.QueryRow(ctx, updateProject, arg.ID, arg.OrgID, arg.Name)
	var i Project
	err := row.Scan(
		&i.ID,
		&i.OrgID,
		&i.Name,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}
