// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: tasks.sql

package db

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const createComment = `-- name: CreateComment :one
INSERT INTO comments (task_id, author_id, body)
VALUES ($1, $2, $3)
RETURNING id, task_id, author_id, body, created_at, updated_at, deleted_at
`

type CreateCommentParams struct {
	TaskID   uuid.UUID `json:"task_id"`
	AuthorID uuid.UUID `json:"author_id"`
	Body     string    `json:"body"`
}

type CreateCommentRow struct {
	ID        uuid.UUID  `json:"id"`
	TaskID    uuid.UUID  `json:"task_id"`
	AuthorID  uuid.UUID  `json:"author_id"`
	Body      string     `json:"body"`
	CreatedAt time.Time  `json:"created_at"`
	UpdatedAt time.Time  `json:"updated_at"`
	DeletedAt *time.Time `json:"deleted_at"`
}

func (q *Queries) CreateComment(ctx context.Context, arg CreateCommentParams) (CreateCommentRow, error) {
	row := q.db.QueryRow(ctx, createComment, arg.TaskID, arg.AuthorID, arg.Body)
	var i CreateCommentRow
	err := row.Scan(
		&i.ID,
		&i.TaskID,
		&i.AuthorID,
		&i.Body,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const createTask = `-- name: CreateTask :one

INSERT INTO tasks (org_id, project_id, title, status, position)
SELECT $1, $2, $3, $4, $5
FROM projects
WHERE projects.id = $2
  AND projects.org_id = $1
  AND projects.deleted_at IS NULL
RETURNING id, org_id, project_id, title, status, position, created_at, updated_at, deleted_at
`

type CreateTaskParams struct {
	OrgID     uuid.UUID `json:"org_id"`
	ProjectID uuid.UUID `json:"project_id"`
	Title     string    `json:"title"`
	Status    string    `json:"status"`
	Position  float64   `json:"position"`
}

// Tasks + comments — every task query scoped by org_id. (Chapter 8 / sqlc)
//
// Chapter 10: delete is soft. Every task read below excludes deleted_at IS
// NOT NULL rows; SoftDeleteTask replaces DeleteTask, and
// SoftDeleteTasksByProject is the cascade a project's own soft delete uses —
// see internal/projects's Delete for why that cascade has to be explicit now
// instead of the ON DELETE CASCADE foreign key it replaces.
//
// deleted_at is selected/returned everywhere below for the same reason
// projects.sql does it — see that file's header — even though every query
// here already guarantees it is NULL.
//
// Comments now have a deleted_at of their own — 0010 added it along with the
// DELETE endpoint whose absence was 0009's stated reason for withholding one.
// So a comment read checks BOTH: the parent task's deleted_at through the
// join, and the comment's own. The join is also where org_id is checked, and
// it closes a latent gap this query had before Chapter 10 touched it: it
// filtered by task_id alone, so an org member who knew another org's task id
// could read its comments.
// INSERT ... SELECT, not VALUES, so the org owns the project or nothing is
// written.
//
// The plain VALUES form checked two foreign keys independently — org_id names
// a real org, project_id names a real project — and never that the two belong
// together. A member of org A could therefore POST a task to org B's project
// id and have it accepted: the row landed with A's org_id and B's project_id.
// It leaked no data (every read here is scoped by org_id, so B never saw it
// and A never saw B's tasks), but it let one tenant write rows referencing
// another tenant's project, and it made the endpoint an existence oracle for
// project ids.
//
// The guard belongs here rather than in a handler for the same reason the rest
// of the org scoping does: a SELECT that finds no matching project inserts no
// row, atomically, on every path that reaches this query — the single-task
// create and the bulk import both — with no extra round trip and nothing for a
// future caller to forget. sqlc's :one then returns pgx.ErrNoRows, which the
// repo maps to ErrNotFound: from outside, a project you cannot write to is
// indistinguishable from one that does not exist, which is the right answer.
func (q *Queries) CreateTask(ctx context.Context, arg CreateTaskParams) (Task, error) {
	row := q.db.QueryRow(ctx, createTask,
		arg.OrgID,
		arg.ProjectID,
		arg.Title,
		arg.Status,
		arg.Position,
	)
	var i Task
	err := row.Scan(
		&i.ID,
		&i.OrgID,
		&i.ProjectID,
		&i.Title,
		&i.Status,
		&i.Position,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const getCommentByID = `-- name: GetCommentByID :one
SELECT comments.id, comments.task_id, comments.author_id, comments.body,
       comments.created_at, comments.updated_at, comments.deleted_at
FROM comments
JOIN tasks ON tasks.id = comments.task_id
WHERE comments.id = $1 AND tasks.org_id = $2
  AND tasks.deleted_at IS NULL AND comments.deleted_at IS NULL
`

type GetCommentByIDParams struct {
	ID    uuid.UUID `json:"id"`
	OrgID uuid.UUID `json:"org_id"`
}

type GetCommentByIDRow struct {
	ID        uuid.UUID  `json:"id"`
	TaskID    uuid.UUID  `json:"task_id"`
	AuthorID  uuid.UUID  `json:"author_id"`
	Body      string     `json:"body"`
	CreatedAt time.Time  `json:"created_at"`
	UpdatedAt time.Time  `json:"updated_at"`
	DeletedAt *time.Time `json:"deleted_at"`
}

// Scoped through the parent task's org, the same join every other comment
// query uses. The service reads this BEFORE an edit or a delete, because both
// decisions need the author id and neither can be made from the request alone.
func (q *Queries) GetCommentByID(ctx context.Context, arg GetCommentByIDParams) (GetCommentByIDRow, error) {
	row := q.db.QueryRow(ctx, getCommentByID, arg.ID, arg.OrgID)
	var i GetCommentByIDRow
	err := row.Scan(
		&i.ID,
		&i.TaskID,
		&i.AuthorID,
		&i.Body,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const getTaskByID = `-- name: GetTaskByID :one
SELECT id, org_id, project_id, title, status, position, created_at, updated_at, deleted_at
FROM tasks
WHERE id = $1 AND org_id = $2 AND deleted_at IS NULL
`

type GetTaskByIDParams struct {
	ID    uuid.UUID `json:"id"`
	OrgID uuid.UUID `json:"org_id"`
}

func (q *Queries) GetTaskByID(ctx context.Context, arg GetTaskByIDParams) (Task, error) {
	row := q.db.QueryRow(ctx, getTaskByID, arg.ID, arg.OrgID)
	var i Task
	err := row.Scan(
		&i.ID,
		&i.OrgID,
		&i.ProjectID,
		&i.Title,
		&i.Status,
		&i.Position,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const listCommentsByTask = `-- name: ListCommentsByTask :many
SELECT comments.id, comments.task_id, comments.author_id, comments.body,
       comments.created_at, comments.updated_at, comments.deleted_at
FROM comments
JOIN tasks ON tasks.id = comments.task_id
WHERE comments.task_id = $1 AND tasks.org_id = $2
  AND tasks.deleted_at IS NULL AND comments.deleted_at IS NULL
ORDER BY comments.created_at ASC
`

type ListCommentsByTaskParams struct {
	TaskID uuid.UUID `json:"task_id"`
	OrgID  uuid.UUID `json:"org_id"`
}

type ListCommentsByTaskRow struct {
	ID        uuid.UUID  `json:"id"`
	TaskID    uuid.UUID  `json:"task_id"`
	AuthorID  uuid.UUID  `json:"author_id"`
	Body      string     `json:"body"`
	CreatedAt time.Time  `json:"created_at"`
	UpdatedAt time.Time  `json:"updated_at"`
	DeletedAt *time.Time `json:"deleted_at"`
}

func (q *Queries) ListCommentsByTask(ctx context.Context, arg ListCommentsByTaskParams) ([]ListCommentsByTaskRow, error) {
	rows, err := q.db.Query(ctx, listCommentsByTask, arg.TaskID, arg.OrgID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListCommentsByTaskRow
	for rows.Next() {
		var i ListCommentsByTaskRow
		if err := rows.Scan(
			&i.ID,
			&i.TaskID,
			&i.AuthorID,
			&i.Body,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTasksByProject = `-- name: ListTasksByProject :many
SELECT id, org_id, project_id, title, status, position, created_at, updated_at, deleted_at
FROM tasks
WHERE org_id = $1 AND project_id = $2 AND deleted_at IS NULL
  AND ($5::text IS NULL OR status = $5)
ORDER BY position ASC, created_at ASC, id ASC
LIMIT $3 OFFSET $4
`

type ListTasksByProjectParams struct {
	OrgID     uuid.UUID `json:"org_id"`
	ProjectID uuid.UUID `json:"project_id"`
	Limit     int32     `json:"limit"`
	Offset    int32     `json:"offset"`
	Status    *string   `json:"status"`
}

// A NULL status arg makes the status filter a no-op (any status).
func (q *Queries) ListTasksByProject(ctx context.Context, arg ListTasksByProjectParams) ([]Task, error) {
	rows, err := q.db.Query(ctx, listTasksByProject,
		arg.OrgID,
		arg.ProjectID,
		arg.Limit,
		arg.Offset,
		arg.Status,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Task
	for rows.Next() {
		var i Task
		if err := rows.Scan(
			&i.ID,
			&i.OrgID,
			&i.ProjectID,
			&i.Title,
			&i.Status,
			&i.Position,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const maxTaskPosition = `-- name: MaxTaskPosition :one
SELECT COALESCE(MAX(position), 0)::float8
FROM tasks
WHERE org_id = $1 AND project_id = $2 AND deleted_at IS NULL
`

type MaxTaskPositionParams struct {
	OrgID     uuid.UUID `json:"org_id"`
	ProjectID uuid.UUID `json:"project_id"`
}

// The highest position currently in a project, for appending imported tasks
// after the existing cards. COALESCE makes an empty project answer 0 rather
// than NULL, so the caller gets a float64 and not a null-handling branch.
func (q *Queries) MaxTaskPosition(ctx context.Context, arg MaxTaskPositionParams) (float64, error) {
	row := q.db.QueryRow(ctx, maxTaskPosition, arg.OrgID, arg.ProjectID)
	var column_1 float64
	err := row.Scan(&column_1)
	return column_1, err
}

const softDeleteComment = `-- name: SoftDeleteComment :execrows
UPDATE comments SET deleted_at = now()
FROM tasks
WHERE comments.id = $1 AND comments.task_id = tasks.id
  AND tasks.org_id = $2
  AND tasks.deleted_at IS NULL AND comments.deleted_at IS NULL
`

type SoftDeleteCommentParams struct {
	ID    uuid.UUID `json:"id"`
	OrgID uuid.UUID `json:"org_id"`
}

// No author_id here, unlike UpdateComment: an org admin may delete a comment
// they did not write (moderation), so the caller check cannot live in the SQL.
// The service decides, and :execrows lets it tell "not yours" from "not there".
func (q *Queries) SoftDeleteComment(ctx context.Context, arg SoftDeleteCommentParams) (int64, error) {
	result, err := q.db.Exec(ctx, softDeleteComment, arg.ID, arg.OrgID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const softDeleteTask = `-- name: SoftDeleteTask :execrows
UPDATE tasks SET deleted_at = now()
WHERE id = $1 AND org_id = $2 AND deleted_at IS NULL
`

type SoftDeleteTaskParams struct {
	ID    uuid.UUID `json:"id"`
	OrgID uuid.UUID `json:"org_id"`
}

func (q *Queries) SoftDeleteTask(ctx context.Context, arg SoftDeleteTaskParams) (int64, error) {
	result, err := q.db.Exec(ctx, softDeleteTask, arg.ID, arg.OrgID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const softDeleteTasksByProject = `-- name: SoftDeleteTasksByProject :exec
UPDATE tasks SET deleted_at = now()
WHERE project_id = $1 AND deleted_at IS NULL
`

// The cascade a project's soft delete performs explicitly, in the same
// transaction, in place of the ON DELETE CASCADE the hard-delete version got
// for free from the foreign key.
func (q *Queries) SoftDeleteTasksByProject(ctx context.Context, projectID uuid.UUID) error {
	_, err := q.db.Exec(ctx, softDeleteTasksByProject, projectID)
	return err
}

const updateComment = `-- name: UpdateComment :one
UPDATE comments SET body = $4, updated_at = now()
FROM tasks
WHERE comments.id = $1 AND comments.task_id = tasks.id
  AND tasks.org_id = $2 AND comments.author_id = $3
  AND tasks.deleted_at IS NULL AND comments.deleted_at IS NULL
RETURNING comments.id, comments.task_id, comments.author_id, comments.body,
          comments.created_at, comments.updated_at, comments.deleted_at
`

type UpdateCommentParams struct {
	ID       uuid.UUID `json:"id"`
	OrgID    uuid.UUID `json:"org_id"`
	AuthorID uuid.UUID `json:"author_id"`
	Body     string    `json:"body"`
}

type UpdateCommentRow struct {
	ID        uuid.UUID  `json:"id"`
	TaskID    uuid.UUID  `json:"task_id"`
	AuthorID  uuid.UUID  `json:"author_id"`
	Body      string     `json:"body"`
	CreatedAt time.Time  `json:"created_at"`
	UpdatedAt time.Time  `json:"updated_at"`
	DeletedAt *time.Time `json:"deleted_at"`
}

// The author_id in the WHERE clause is the authorisation, not just a filter.
// The service checks it too and returns a clearer error, but repeating it here
// means no future caller can edit somebody else's words by reaching the repo
// directly — the same argument as CreateTask's INSERT ... SELECT.
func (q *Queries) UpdateComment(ctx context.Context, arg UpdateCommentParams) (UpdateCommentRow, error) {
	row := q.db.QueryRow(ctx, updateComment,
		arg.ID,
		arg.OrgID,
		arg.AuthorID,
		arg.Body,
	)
	var i UpdateCommentRow
	err := row.Scan(
		&i.ID,
		&i.TaskID,
		&i.AuthorID,
		&i.Body,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const updateTask = `-- name: UpdateTask :one
UPDATE tasks SET title = $3, status = $4, position = $5, updated_at = now()
WHERE id = $1 AND org_id = $2 AND deleted_at IS NULL
RETURNING id, org_id, project_id, title, status, position, created_at, updated_at, deleted_at
`

type UpdateTaskParams struct {
	ID       uuid.UUID `json:"id"`
	OrgID    uuid.UUID `json:"org_id"`
	Title    string    `json:"title"`
	Status   string    `json:"status"`
	Position float64   `json:"position"`
}

func (q *Queries) UpdateTask(ctx context.Context, arg UpdateTaskParams) (Task, error) {
	row := q.db.QueryRow(ctx, updateTask,
		arg.ID,
		arg.OrgID,
		arg.Title,
		arg.Status,
		arg.Position,
	)
	var i Task
	err := row.Scan(
		&i.ID,
		&i.OrgID,
		&i.ProjectID,
		&i.Title,
		&i.Status,
		&i.Position,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}
