// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: webhooks.sql

package db

import (
	"context"

	"github.com/google/uuid"
)

const activeWebhooksForEvent = `-- name: ActiveWebhooksForEvent :many
SELECT id, org_id, url, secret, events, active, created_at, deleted_at
FROM webhooks
WHERE org_id = $1 AND active = true AND deleted_at IS NULL
  AND (cardinality(events) = 0 OR $2::text = ANY(events))
ORDER BY created_at ASC
`

type ActiveWebhooksForEventParams struct {
	OrgID uuid.UUID `json:"org_id"`
	Event string    `json:"event"`
}

func (q *Queries) ActiveWebhooksForEvent(ctx context.Context, arg ActiveWebhooksForEventParams) ([]Webhook, error) {
	rows, err := q.db.Query(ctx, activeWebhooksForEvent, arg.OrgID, arg.Event)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Webhook
	for rows.Next() {
		var i Webhook
		if err := rows.Scan(
			&i.ID,
			&i.OrgID,
			&i.Url,
			&i.Secret,
			&i.Events,
			&i.Active,
			&i.CreatedAt,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const createDelivery = `-- name: CreateDelivery :one
INSERT INTO webhook_deliveries (webhook_id, event, payload)
VALUES ($1, $2, $3)
RETURNING id
`

type CreateDeliveryParams struct {
	WebhookID uuid.UUID `json:"webhook_id"`
	Event     string    `json:"event"`
	Payload   []byte    `json:"payload"`
}

func (q *Queries) CreateDelivery(ctx context.Context, arg CreateDeliveryParams) (uuid.UUID, error) {
	row := q.db.QueryRow(ctx, createDelivery, arg.WebhookID, arg.Event, arg.Payload)
	var id uuid.UUID
	err := row.Scan(&id)
	return id, err
}

const createWebhook = `-- name: CreateWebhook :one

INSERT INTO webhooks (org_id, url, secret, events)
VALUES ($1, $2, $3, $4)
RETURNING id, org_id, url, secret, events, active, created_at, deleted_at
`

type CreateWebhookParams struct {
	OrgID  uuid.UUID `json:"org_id"`
	Url    string    `json:"url"`
	Secret string    `json:"secret"`
	Events []string  `json:"events"`
}

// Webhooks + deliveries — webhooks scoped by org_id; deliveries by webhook_id.
// (Chapter 8 / sqlc)
//
// Chapter 10: delete is soft. ActiveWebhooksForEvent and GetWebhook both gain
// the deleted_at check — the first so a soft-deleted webhook stops receiving
// new events, the second so the delivery worker (which loads a webhook by id
// alone, unscoped by org, to sign a payload) stops finding one that should no
// longer exist.
//
// deleted_at is selected/returned everywhere below for the same reason
// projects.sql does it — see that file's header — even though every query
// here already guarantees it is NULL.
func (q *Queries) CreateWebhook(ctx context.Context, arg CreateWebhookParams) (Webhook, error) {
	row := q.db.QueryRow(ctx, createWebhook,
		arg.OrgID,
		arg.Url,
		arg.Secret,
		arg.Events,
	)
	var i Webhook
	err := row.Scan(
		&i.ID,
		&i.OrgID,
		&i.Url,
		&i.Secret,
		&i.Events,
		&i.Active,
		&i.CreatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const getWebhook = `-- name: GetWebhook :one
SELECT id, org_id, url, secret, events, active, created_at, deleted_at
FROM webhooks
WHERE id = $1 AND deleted_at IS NULL
`

func (q *Queries) GetWebhook(ctx context.Context, id uuid.UUID) (Webhook, error) {
	row := q.db.QueryRow(ctx, getWebhook, id)
	var i Webhook
	err := row.Scan(
		&i.ID,
		&i.OrgID,
		&i.Url,
		&i.Secret,
		&i.Events,
		&i.Active,
		&i.CreatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const getWebhookByOrg = `-- name: GetWebhookByOrg :one
SELECT id, org_id, url, secret, events, active, created_at, deleted_at
FROM webhooks
WHERE id = $1 AND org_id = $2 AND deleted_at IS NULL
`

type GetWebhookByOrgParams struct {
	ID    uuid.UUID `json:"id"`
	OrgID uuid.UUID `json:"org_id"`
}

func (q *Queries) GetWebhookByOrg(ctx context.Context, arg GetWebhookByOrgParams) (Webhook, error) {
	row := q.db.QueryRow(ctx, getWebhookByOrg, arg.ID, arg.OrgID)
	var i Webhook
	err := row.Scan(
		&i.ID,
		&i.OrgID,
		&i.Url,
		&i.Secret,
		&i.Events,
		&i.Active,
		&i.CreatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const listWebhooksByOrg = `-- name: ListWebhooksByOrg :many
SELECT id, org_id, url, secret, events, active, created_at, deleted_at
FROM webhooks
WHERE org_id = $1 AND deleted_at IS NULL
ORDER BY created_at DESC
`

func (q *Queries) ListWebhooksByOrg(ctx context.Context, orgID uuid.UUID) ([]Webhook, error) {
	rows, err := q.db.Query(ctx, listWebhooksByOrg, orgID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Webhook
	for rows.Next() {
		var i Webhook
		if err := rows.Scan(
			&i.ID,
			&i.OrgID,
			&i.Url,
			&i.Secret,
			&i.Events,
			&i.Active,
			&i.CreatedAt,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markDeliveryStatus = `-- name: MarkDeliveryStatus :exec
UPDATE webhook_deliveries
SET status = $2, attempts = $3, last_error = $4
WHERE id = $1
`

type MarkDeliveryStatusParams struct {
	ID        uuid.UUID `json:"id"`
	Status    string    `json:"status"`
	Attempts  int32     `json:"attempts"`
	LastError string    `json:"last_error"`
}

func (q *Queries) MarkDeliveryStatus(ctx context.Context, arg MarkDeliveryStatusParams) error {
	_, err := q.db.Exec(ctx, markDeliveryStatus,
		arg.ID,
		arg.Status,
		arg.Attempts,
		arg.LastError,
	)
	return err
}

const markDeliverySuccess = `-- name: MarkDeliverySuccess :exec
UPDATE webhook_deliveries
SET status = 'success', attempts = $2, last_error = '', delivered_at = now()
WHERE id = $1
`

type MarkDeliverySuccessParams struct {
	ID       uuid.UUID `json:"id"`
	Attempts int32     `json:"attempts"`
}

func (q *Queries) MarkDeliverySuccess(ctx context.Context, arg MarkDeliverySuccessParams) error {
	_, err := q.db.Exec(ctx, markDeliverySuccess, arg.ID, arg.Attempts)
	return err
}

const softDeleteWebhook = `-- name: SoftDeleteWebhook :execrows
UPDATE webhooks SET deleted_at = now()
WHERE id = $1 AND org_id = $2 AND deleted_at IS NULL
`

type SoftDeleteWebhookParams struct {
	ID    uuid.UUID `json:"id"`
	OrgID uuid.UUID `json:"org_id"`
}

func (q *Queries) SoftDeleteWebhook(ctx context.Context, arg SoftDeleteWebhookParams) (int64, error) {
	result, err := q.db.Exec(ctx, softDeleteWebhook, arg.ID, arg.OrgID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}
