// Package users owns identity: the User model, a hand-written pgx repository,
// and a service with Signup and Login. A user lives OUTSIDE any organization
// (the one table with no org_id); organizations reach a user through the
// memberships join.
//
// Course mapping: Chapter 15 — password hashing (Signup/Login use auth.Hash /
// auth.Verify); Chapter 16 — Login issues a JWT; Chapter 21 — service layer.
//
// Course mapping: Chapter 8 — the repository's queries are now generated by
// sqlc (internal/db). The methods below call the generated query functions and
// map the sqlc row structs into this package's User domain struct. UUIDs cross
// the package boundary as strings (the domain struct exposes them as strings),
// so each method parses inbound IDs into uuid.UUID and stringifies outbound ones.
package users

import (
	"context"
	"errors"
	"fmt"
	"time"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5"
	"github.com/jackc/pgx/v5/pgxpool"

	"beacon/internal/auth"
	"beacon/internal/db"
	"beacon/internal/pgerr"
)

// Sentinel errors. The HTTP layer maps these to status codes.
var (
	ErrEmailTaken         = errors.New("email already registered")
	ErrInvalidCredentials = errors.New("invalid credentials")
	ErrNotFound           = errors.New("user not found")
)

// User is the identity model. PasswordHash is never serialised to JSON.
type User struct {
	ID           string    `json:"id"`
	Email        string    `json:"email"`
	Name         string    `json:"name"`
	PasswordHash string    `json:"-"`
	CreatedAt    time.Time `json:"created_at"`
}

// Repo is the user repository backed by sqlc-generated queries.
type Repo struct {
	q *db.Queries
}

func NewRepo(pool *pgxpool.Pool) *Repo { return &Repo{q: db.New(pool)} }

// Create inserts a user and returns the stored row. A duplicate email (the
// unique lower(email) index) surfaces as ErrEmailTaken.
func (r *Repo) Create(ctx context.Context, email, name, passwordHash string) (User, error) {
	row, err := r.q.CreateUser(ctx, db.CreateUserParams{
		Email:        email,
		Name:         name,
		PasswordHash: passwordHash,
	})
	if err != nil {
		if pgerr.IsUniqueViolation(err) {
			return User{}, ErrEmailTaken
		}
		return User{}, fmt.Errorf("users.Create: %w", err)
	}
	return User{
		ID:           row.ID.String(),
		Email:        row.Email,
		Name:         row.Name,
		PasswordHash: row.PasswordHash,
		CreatedAt:    row.CreatedAt,
	}, nil
}

// GetByEmail looks a user up by email (case-insensitive).
func (r *Repo) GetByEmail(ctx context.Context, email string) (User, error) {
	row, err := r.q.GetUserByEmail(ctx, email)
	if err != nil {
		if errors.Is(err, pgx.ErrNoRows) {
			return User{}, ErrNotFound
		}
		return User{}, fmt.Errorf("users.GetByEmail: %w", err)
	}
	return User{
		ID:           row.ID.String(),
		Email:        row.Email,
		Name:         row.Name,
		PasswordHash: row.PasswordHash,
		CreatedAt:    row.CreatedAt,
	}, nil
}

// GetByID looks a user up by id.
func (r *Repo) GetByID(ctx context.Context, id string) (User, error) {
	uid, err := uuid.Parse(id)
	if err != nil {
		return User{}, ErrNotFound // a malformed id can match no row
	}
	row, err := r.q.GetUserByID(ctx, uid)
	if err != nil {
		if errors.Is(err, pgx.ErrNoRows) {
			return User{}, ErrNotFound
		}
		return User{}, fmt.Errorf("users.GetByID: %w", err)
	}
	return User{
		ID:           row.ID.String(),
		Email:        row.Email,
		Name:         row.Name,
		PasswordHash: row.PasswordHash,
		CreatedAt:    row.CreatedAt,
	}, nil
}

// Service holds the user business rules.
type Service struct {
	repo      *Repo
	jwtSecret string
	jwtTTL    time.Duration
}

func NewService(repo *Repo, jwtSecret string, jwtTTL time.Duration) *Service {
	return &Service{repo: repo, jwtSecret: jwtSecret, jwtTTL: jwtTTL}
}

// Signup hashes the password and creates the user.
func (s *Service) Signup(ctx context.Context, email, name, password string) (User, error) {
	hash, err := auth.Hash(password)
	if err != nil {
		return User{}, fmt.Errorf("users.Signup: hash: %w", err)
	}
	return s.repo.Create(ctx, email, name, hash)
}

// Login verifies the password and, on success, returns the user and a signed
// access token. Wrong email and wrong password both return ErrInvalidCredentials
// so the response never reveals which accounts exist.
func (s *Service) Login(ctx context.Context, email, password string) (User, string, error) {
	u, err := s.repo.GetByEmail(ctx, email)
	if err != nil {
		if errors.Is(err, ErrNotFound) {
			return User{}, "", ErrInvalidCredentials
		}
		return User{}, "", fmt.Errorf("users.Login: lookup: %w", err)
	}

	ok, err := auth.Verify(password, u.PasswordHash)
	if err != nil {
		return User{}, "", fmt.Errorf("users.Login: verify: %w", err)
	}
	if !ok {
		return User{}, "", ErrInvalidCredentials
	}

	token, err := auth.IssueToken(s.jwtSecret, u.ID, s.jwtTTL)
	if err != nil {
		return User{}, "", fmt.Errorf("users.Login: issue: %w", err)
	}
	return u, token, nil
}

// GetByID is a thin pass-through the HTTP /me handler uses.
func (s *Service) GetByID(ctx context.Context, id string) (User, error) {
	return s.repo.GetByID(ctx, id)
}
