// Package tasks owns tasks and their comments. Tasks belong to projects;
// comments belong to tasks. Everything is scoped by org_id so the tenant
// boundary holds on every read and write. Status is constrained to the set
// {todo, in_progress, done}.
//
// Course mapping: Chapter 7 — org scoping; Chapter 11 — status validation;
// Chapter 13 — pagination + status filter; Chapter 21 — service layer.
//
// Course mapping: Chapter 8 — queries generated by sqlc (internal/db). The
// methods call the generated functions and map rows into Task / Comment. UUIDs
// cross the boundary as text. The org_id scope lives in every task query.
package tasks

import (
	"context"
	"errors"
	"fmt"
	"time"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5"
	"github.com/jackc/pgx/v5/pgxpool"

	"beacon/internal/db"
)

// Sentinel errors.
var (
	ErrNotFound      = errors.New("task not found")
	ErrInvalidStatus = errors.New("invalid task status")
)

// Valid task statuses (matches the CHECK constraint in 0001_init.up.sql).
const (
	StatusTodo       = "todo"
	StatusInProgress = "in_progress"
	StatusDone       = "done"
)

// ValidStatus reports whether s is an allowed status.
func ValidStatus(s string) bool {
	return s == StatusTodo || s == StatusInProgress || s == StatusDone
}

// Task belongs to a project (and, denormalised, an org).
type Task struct {
	ID        string    `json:"id"`
	OrgID     string    `json:"org_id"`
	ProjectID string    `json:"project_id"`
	Title     string    `json:"title"`
	Status    string    `json:"status"`
	Position  float64   `json:"position"`
	CreatedAt time.Time `json:"created_at"`
	UpdatedAt time.Time `json:"updated_at"`
}

// Comment belongs to a task.
type Comment struct {
	ID        string    `json:"id"`
	TaskID    string    `json:"task_id"`
	AuthorID  string    `json:"author_id"`
	Body      string    `json:"body"`
	CreatedAt time.Time `json:"created_at"`
}

// Repo is the tasks + comments repository backed by sqlc-generated queries.
// Every task method takes org_id; comment methods inherit the scope via the
// parent task lookup the service performs first.
type Repo struct {
	q *db.Queries
}

func NewRepo(pool *pgxpool.Pool) *Repo { return &Repo{q: db.New(pool)} }

func toTask(t db.Task) Task {
	return Task{
		ID:        t.ID.String(),
		OrgID:     t.OrgID.String(),
		ProjectID: t.ProjectID.String(),
		Title:     t.Title,
		Status:    t.Status,
		Position:  t.Position,
		CreatedAt: t.CreatedAt,
		UpdatedAt: t.UpdatedAt,
	}
}

func toComment(c db.Comment) Comment {
	return Comment{
		ID:        c.ID.String(),
		TaskID:    c.TaskID.String(),
		AuthorID:  c.AuthorID.String(),
		Body:      c.Body,
		CreatedAt: c.CreatedAt,
	}
}

// Create inserts a task in the given org + project.
func (r *Repo) Create(ctx context.Context, orgID, projectID, title, status string, position float64) (Task, error) {
	oid, err := uuid.Parse(orgID)
	if err != nil {
		return Task{}, fmt.Errorf("tasks.Create: parse org id: %w", err)
	}
	pid, err := uuid.Parse(projectID)
	if err != nil {
		return Task{}, fmt.Errorf("tasks.Create: parse project id: %w", err)
	}
	t, err := r.q.CreateTask(ctx, db.CreateTaskParams{
		OrgID:     oid,
		ProjectID: pid,
		Title:     title,
		Status:    status,
		Position:  position,
	})
	if err != nil {
		return Task{}, fmt.Errorf("tasks.Create: %w", err)
	}
	return toTask(t), nil
}

// ListByProject returns one page of a project's tasks, optionally filtered by
// status. Scoped by org. An empty status means "any status".
func (r *Repo) ListByProject(ctx context.Context, orgID, projectID, status string, limit, offset int) ([]Task, error) {
	oid, err := uuid.Parse(orgID)
	if err != nil {
		return []Task{}, nil
	}
	pid, err := uuid.Parse(projectID)
	if err != nil {
		return []Task{}, nil
	}

	// A nil status pointer makes the status clause a no-op (any status).
	var statusArg *string
	if status != "" {
		statusArg = &status
	}

	rows, err := r.q.ListTasksByProject(ctx, db.ListTasksByProjectParams{
		OrgID:     oid,
		ProjectID: pid,
		Status:    statusArg,
		Limit:     int32(limit),
		Offset:    int32(offset),
	})
	if err != nil {
		return nil, fmt.Errorf("tasks.ListByProject: %w", err)
	}
	out := make([]Task, 0, len(rows))
	for _, t := range rows {
		out = append(out, toTask(t))
	}
	return out, nil
}

// GetByID returns a task scoped to its org; a mismatch is ErrNotFound.
func (r *Repo) GetByID(ctx context.Context, orgID, id string) (Task, error) {
	tid, err := uuid.Parse(id)
	if err != nil {
		return Task{}, ErrNotFound
	}
	oid, err := uuid.Parse(orgID)
	if err != nil {
		return Task{}, ErrNotFound
	}
	t, err := r.q.GetTaskByID(ctx, db.GetTaskByIDParams{ID: tid, OrgID: oid})
	if err != nil {
		if errors.Is(err, pgx.ErrNoRows) {
			return Task{}, ErrNotFound
		}
		return Task{}, fmt.Errorf("tasks.GetByID: %w", err)
	}
	return toTask(t), nil
}

// Update changes a task's title, status, and position, scoped by org.
func (r *Repo) Update(ctx context.Context, orgID, id, title, status string, position float64) (Task, error) {
	tid, err := uuid.Parse(id)
	if err != nil {
		return Task{}, ErrNotFound
	}
	oid, err := uuid.Parse(orgID)
	if err != nil {
		return Task{}, ErrNotFound
	}
	t, err := r.q.UpdateTask(ctx, db.UpdateTaskParams{
		ID:       tid,
		OrgID:    oid,
		Title:    title,
		Status:   status,
		Position: position,
	})
	if err != nil {
		if errors.Is(err, pgx.ErrNoRows) {
			return Task{}, ErrNotFound
		}
		return Task{}, fmt.Errorf("tasks.Update: %w", err)
	}
	return toTask(t), nil
}

// Delete removes a task, scoped by org. ErrNotFound if no such row in org.
func (r *Repo) Delete(ctx context.Context, orgID, id string) error {
	tid, err := uuid.Parse(id)
	if err != nil {
		return ErrNotFound
	}
	oid, err := uuid.Parse(orgID)
	if err != nil {
		return ErrNotFound
	}
	n, err := r.q.DeleteTask(ctx, db.DeleteTaskParams{ID: tid, OrgID: oid})
	if err != nil {
		return fmt.Errorf("tasks.Delete: %w", err)
	}
	if n == 0 {
		return ErrNotFound
	}
	return nil
}

// CreateComment inserts a comment on a task.
func (r *Repo) CreateComment(ctx context.Context, taskID, authorID, body string) (Comment, error) {
	tid, err := uuid.Parse(taskID)
	if err != nil {
		return Comment{}, fmt.Errorf("tasks.CreateComment: parse task id: %w", err)
	}
	aid, err := uuid.Parse(authorID)
	if err != nil {
		return Comment{}, fmt.Errorf("tasks.CreateComment: parse author id: %w", err)
	}
	c, err := r.q.CreateComment(ctx, db.CreateCommentParams{TaskID: tid, AuthorID: aid, Body: body})
	if err != nil {
		return Comment{}, fmt.Errorf("tasks.CreateComment: %w", err)
	}
	return toComment(c), nil
}

// ListByTask returns every comment on a task, oldest first.
func (r *Repo) ListByTask(ctx context.Context, taskID string) ([]Comment, error) {
	tid, err := uuid.Parse(taskID)
	if err != nil {
		return []Comment{}, nil
	}
	rows, err := r.q.ListCommentsByTask(ctx, tid)
	if err != nil {
		return nil, fmt.Errorf("tasks.ListByTask: %w", err)
	}
	out := make([]Comment, 0, len(rows))
	for _, c := range rows {
		out = append(out, toComment(c))
	}
	return out, nil
}

// Service holds the task business rules: status validation and org scoping.
type Service struct {
	repo *Repo
}

func NewService(repo *Repo) *Service { return &Service{repo: repo} }

// Create makes a new task. Status defaults to "todo"; a supplied status must
// be valid.
func (s *Service) Create(ctx context.Context, orgID, projectID, title, status string, position float64) (Task, error) {
	if status == "" {
		status = StatusTodo
	}
	if !ValidStatus(status) {
		return Task{}, ErrInvalidStatus
	}
	return s.repo.Create(ctx, orgID, projectID, title, status, position)
}

// List returns a page of a project's tasks, optionally filtered by status.
func (s *Service) List(ctx context.Context, orgID, projectID, status string, limit, offset int) ([]Task, error) {
	if status != "" && !ValidStatus(status) {
		return nil, ErrInvalidStatus
	}
	return s.repo.ListByProject(ctx, orgID, projectID, status, limit, offset)
}

// Get returns a single task, scoped by org.
func (s *Service) Get(ctx context.Context, orgID, id string) (Task, error) {
	return s.repo.GetByID(ctx, orgID, id)
}

// Update changes a task's title/status/position after validating status.
func (s *Service) Update(ctx context.Context, orgID, id, title, status string, position float64) (Task, error) {
	if !ValidStatus(status) {
		return Task{}, ErrInvalidStatus
	}
	return s.repo.Update(ctx, orgID, id, title, status, position)
}

// Delete removes a task, scoped by org.
func (s *Service) Delete(ctx context.Context, orgID, id string) error {
	return s.repo.Delete(ctx, orgID, id)
}

// AddComment confirms the task exists in the caller's org, then writes the
// comment. Scoping the parent task by org keeps comments tenant-safe.
func (s *Service) AddComment(ctx context.Context, orgID, taskID, authorID, body string) (Comment, error) {
	if _, err := s.repo.GetByID(ctx, orgID, taskID); err != nil {
		return Comment{}, err
	}
	return s.repo.CreateComment(ctx, taskID, authorID, body)
}

// Comments lists a task's comments after confirming the task is in the org.
func (s *Service) Comments(ctx context.Context, orgID, taskID string) ([]Comment, error) {
	if _, err := s.repo.GetByID(ctx, orgID, taskID); err != nil {
		return nil, err
	}
	return s.repo.ListByTask(ctx, taskID)
}
