// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: flags.sql

package db

import (
	"context"

	"github.com/google/uuid"
)

const getFeatureFlag = `-- name: GetFeatureFlag :one

SELECT name, description, default_value, created_at, updated_at
FROM feature_flags
WHERE name = $1
`

// Chapter 31 — feature flags. Two reads on the hot path, both cached for 30
// seconds; the rest are the admin surface.
//
// [verbatim ch31, expressed as the sqlc queries the chapter's service calls.]
func (q *Queries) GetFeatureFlag(ctx context.Context, name string) (FeatureFlag, error) {
	row := q.db.QueryRow(ctx, getFeatureFlag, name)
	var i FeatureFlag
	err := row.Scan(
		&i.Name,
		&i.Description,
		&i.DefaultValue,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listFeatureFlagOverrides = `-- name: ListFeatureFlagOverrides :many
SELECT flag_name, org_id, user_id, value, created_at
FROM feature_flag_overrides
WHERE flag_name = $1
`

func (q *Queries) ListFeatureFlagOverrides(ctx context.Context, flagName string) ([]FeatureFlagOverride, error) {
	rows, err := q.db.Query(ctx, listFeatureFlagOverrides, flagName)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []FeatureFlagOverride
	for rows.Next() {
		var i FeatureFlagOverride
		if err := rows.Scan(
			&i.FlagName,
			&i.OrgID,
			&i.UserID,
			&i.Value,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listFeatureFlags = `-- name: ListFeatureFlags :many
SELECT name, description, default_value, created_at, updated_at
FROM feature_flags
ORDER BY name
`

func (q *Queries) ListFeatureFlags(ctx context.Context) ([]FeatureFlag, error) {
	rows, err := q.db.Query(ctx, listFeatureFlags)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []FeatureFlag
	for rows.Next() {
		var i FeatureFlag
		if err := rows.Scan(
			&i.Name,
			&i.Description,
			&i.DefaultValue,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const setFeatureFlagDefault = `-- name: SetFeatureFlagDefault :exec
UPDATE feature_flags SET default_value = $2, updated_at = now() WHERE name = $1
`

type SetFeatureFlagDefaultParams struct {
	Name         string `json:"name"`
	DefaultValue bool   `json:"default_value"`
}

func (q *Queries) SetFeatureFlagDefault(ctx context.Context, arg SetFeatureFlagDefaultParams) error {
	_, err := q.db.Exec(ctx, setFeatureFlagDefault, arg.Name, arg.DefaultValue)
	return err
}

const upsertOrgFlagOverride = `-- name: UpsertOrgFlagOverride :exec
INSERT INTO feature_flag_overrides (flag_name, org_id, value)
VALUES ($1, $2, $3)
ON CONFLICT (flag_name, org_id) WHERE org_id IS NOT NULL
DO UPDATE SET value = EXCLUDED.value
`

type UpsertOrgFlagOverrideParams struct {
	FlagName string     `json:"flag_name"`
	OrgID    *uuid.UUID `json:"org_id"`
	Value    bool       `json:"value"`
}

func (q *Queries) UpsertOrgFlagOverride(ctx context.Context, arg UpsertOrgFlagOverrideParams) error {
	_, err := q.db.Exec(ctx, upsertOrgFlagOverride, arg.FlagName, arg.OrgID, arg.Value)
	return err
}

const upsertUserFlagOverride = `-- name: UpsertUserFlagOverride :exec
INSERT INTO feature_flag_overrides (flag_name, user_id, value)
VALUES ($1, $2, $3)
ON CONFLICT (flag_name, user_id) WHERE user_id IS NOT NULL
DO UPDATE SET value = EXCLUDED.value
`

type UpsertUserFlagOverrideParams struct {
	FlagName string     `json:"flag_name"`
	UserID   *uuid.UUID `json:"user_id"`
	Value    bool       `json:"value"`
}

func (q *Queries) UpsertUserFlagOverride(ctx context.Context, arg UpsertUserFlagOverrideParams) error {
	_, err := q.db.Exec(ctx, upsertUserFlagOverride, arg.FlagName, arg.UserID, arg.Value)
	return err
}
