// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package db

import (
	"context"

	"github.com/google/uuid"
)

type Querier interface {
	ActiveWebhooksForEvent(ctx context.Context, arg ActiveWebhooksForEventParams) ([]Webhook, error)
	AddMembership(ctx context.Context, arg AddMembershipParams) (Membership, error)
	CreateAttachment(ctx context.Context, arg CreateAttachmentParams) (Attachment, error)
	CreateComment(ctx context.Context, arg CreateCommentParams) (Comment, error)
	CreateDelivery(ctx context.Context, arg CreateDeliveryParams) (uuid.UUID, error)
	// Organizations + memberships — the multi-tenant core. (Chapter 8 / sqlc)
	CreateOrg(ctx context.Context, arg CreateOrgParams) (CreateOrgRow, error)
	// Projects — every query scoped by org_id (the tenant boundary). (Chapter 8 / sqlc)
	CreateProject(ctx context.Context, arg CreateProjectParams) (Project, error)
	// Tasks + comments — every task query scoped by org_id. (Chapter 8 / sqlc)
	CreateTask(ctx context.Context, arg CreateTaskParams) (Task, error)
	// Users — identity. The one table with no org_id. (Chapter 8 / sqlc)
	CreateUser(ctx context.Context, arg CreateUserParams) (CreateUserRow, error)
	// Webhooks + deliveries — webhooks scoped by org_id; deliveries by webhook_id.
	// (Chapter 8 / sqlc)
	CreateWebhook(ctx context.Context, arg CreateWebhookParams) (Webhook, error)
	DeleteProject(ctx context.Context, arg DeleteProjectParams) (int64, error)
	DeleteTask(ctx context.Context, arg DeleteTaskParams) (int64, error)
	DeleteWebhook(ctx context.Context, arg DeleteWebhookParams) (int64, error)
	FindUserIDByEmail(ctx context.Context, lower string) (uuid.UUID, error)
	GetAttachmentByID(ctx context.Context, arg GetAttachmentByIDParams) (Attachment, error)
	GetMembership(ctx context.Context, arg GetMembershipParams) (Membership, error)
	GetProjectByID(ctx context.Context, arg GetProjectByIDParams) (Project, error)
	GetTaskByID(ctx context.Context, arg GetTaskByIDParams) (Task, error)
	GetUserByEmail(ctx context.Context, lower string) (GetUserByEmailRow, error)
	GetUserByID(ctx context.Context, id uuid.UUID) (GetUserByIDRow, error)
	GetWebhook(ctx context.Context, id uuid.UUID) (Webhook, error)
	GetWebhookByOrg(ctx context.Context, arg GetWebhookByOrgParams) (Webhook, error)
	ListAttachmentsByTask(ctx context.Context, arg ListAttachmentsByTaskParams) ([]Attachment, error)
	ListCommentsByTask(ctx context.Context, taskID uuid.UUID) ([]Comment, error)
	ListMembers(ctx context.Context, orgID uuid.UUID) ([]ListMembersRow, error)
	ListOrgsForUser(ctx context.Context, userID uuid.UUID) ([]ListOrgsForUserRow, error)
	ListProjectsByOrg(ctx context.Context, arg ListProjectsByOrgParams) ([]Project, error)
	// A NULL status arg makes the status filter a no-op (any status).
	ListTasksByProject(ctx context.Context, arg ListTasksByProjectParams) ([]Task, error)
	ListWebhooksByOrg(ctx context.Context, orgID uuid.UUID) ([]Webhook, error)
	MarkDeliveryStatus(ctx context.Context, arg MarkDeliveryStatusParams) error
	MarkDeliverySuccess(ctx context.Context, arg MarkDeliverySuccessParams) error
	// Attachments — no org_id of their own; scoped by joining through tasks.org_id.
	// (Chapter 8 / sqlc)
	TaskInOrg(ctx context.Context, arg TaskInOrgParams) (bool, error)
	UpdateProject(ctx context.Context, arg UpdateProjectParams) (Project, error)
	UpdateTask(ctx context.Context, arg UpdateTaskParams) (Task, error)
}

var _ Querier = (*Queries)(nil)
