// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: search.sql

package db

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const getSearchDocument = `-- name: GetSearchDocument :one
SELECT
    si.organization_id,
    si.entity_kind,
    si.entity_id,
    si.title,
    si.body,
    si.updated_at
FROM search_index si
WHERE si.entity_kind = $1 AND si.entity_id = $2
`

type GetSearchDocumentParams struct {
	EntityKind string    `json:"entity_kind"`
	EntityID   uuid.UUID `json:"entity_id"`
}

type GetSearchDocumentRow struct {
	OrganizationID uuid.UUID `json:"organization_id"`
	EntityKind     string    `json:"entity_kind"`
	EntityID       uuid.UUID `json:"entity_id"`
	Title          string    `json:"title"`
	Body           string    `json:"body"`
	UpdatedAt      time.Time `json:"updated_at"`
}

// Chapter 30's write path loads the canonical row out of Postgres before
// pushing it to Meilisearch. Postgres is authoritative; Meili is a copy.
func (q *Queries) GetSearchDocument(ctx context.Context, arg GetSearchDocumentParams) (GetSearchDocumentRow, error) {
	row := q.db.QueryRow(ctx, getSearchDocument, arg.EntityKind, arg.EntityID)
	var i GetSearchDocumentRow
	err := row.Scan(
		&i.OrganizationID,
		&i.EntityKind,
		&i.EntityID,
		&i.Title,
		&i.Body,
		&i.UpdatedAt,
	)
	return i, err
}

const listSearchDocuments = `-- name: ListSearchDocuments :many
SELECT
    si.id,
    si.organization_id,
    si.entity_kind,
    si.entity_id,
    si.title,
    si.body,
    si.updated_at
FROM search_index si
WHERE ($3::uuid IS NULL OR si.organization_id = $3::uuid)
  AND si.id > $1
ORDER BY si.id
LIMIT $2
`

type ListSearchDocumentsParams struct {
	ID    uuid.UUID  `json:"id"`
	Limit int32      `json:"limit"`
	OrgID *uuid.UUID `json:"org_id"`
}

type ListSearchDocumentsRow struct {
	ID             uuid.UUID `json:"id"`
	OrganizationID uuid.UUID `json:"organization_id"`
	EntityKind     string    `json:"entity_kind"`
	EntityID       uuid.UUID `json:"entity_id"`
	Title          string    `json:"title"`
	Body           string    `json:"body"`
	UpdatedAt      time.Time `json:"updated_at"`
}

// The batched full reindex (Chapter 30). Keyset pagination on the primary key
// so a reindex of a large org doesn't OFFSET its way into a slow crawl.
func (q *Queries) ListSearchDocuments(ctx context.Context, arg ListSearchDocumentsParams) ([]ListSearchDocumentsRow, error) {
	rows, err := q.db.Query(ctx, listSearchDocuments, arg.ID, arg.Limit, arg.OrgID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListSearchDocumentsRow
	for rows.Next() {
		var i ListSearchDocumentsRow
		if err := rows.Scan(
			&i.ID,
			&i.OrganizationID,
			&i.EntityKind,
			&i.EntityID,
			&i.Title,
			&i.Body,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const searchOrg = `-- name: SearchOrg :many

SELECT
    si.entity_kind,
    si.entity_id,
    si.title,
    ts_headline('english', si.body, plainto_tsquery('english', $2),
                'StartSel=<mark>, StopSel=</mark>, MaxWords=25, MinWords=10') AS snippet,
    ts_rank(si.search_vector, plainto_tsquery('english', $2)) AS rank
FROM search_index si
WHERE si.organization_id = $1
  AND si.search_vector @@ plainto_tsquery('english', $2)
ORDER BY rank DESC, si.updated_at DESC
LIMIT $3 OFFSET $4
`

type SearchOrgParams struct {
	OrganizationID uuid.UUID `json:"organization_id"`
	PlaintoTsquery string    `json:"plainto_tsquery"`
	Limit          int32     `json:"limit"`
	Offset         int32     `json:"offset"`
}

type SearchOrgRow struct {
	EntityKind string    `json:"entity_kind"`
	EntityID   uuid.UUID `json:"entity_id"`
	Title      string    `json:"title"`
	Snippet    []byte    `json:"snippet"`
	Rank       float32   `json:"rank"`
}

// Chapter 29 — the tenant-scoped full-text query.
//
// Four functions carry it. plainto_tsquery turns the user's words into a
// tsquery safely (never glue strings into to_tsquery — that is SQL injection in
// a disguise). @@ is the match operator. ts_rank scores using the A/B/C weights
// the trigger set. ts_headline returns the matching slice of the body wrapped
// in <mark>, which is what makes a result look like a real search result.
//
// The WHERE clause starts with organization_id. That ordering is not
// cosmetic — it is the reason one tenant can never see another's rows.
//
// [verbatim ch29]
func (q *Queries) SearchOrg(ctx context.Context, arg SearchOrgParams) ([]SearchOrgRow, error) {
	rows, err := q.db.Query(ctx, searchOrg,
		arg.OrganizationID,
		arg.PlaintoTsquery,
		arg.Limit,
		arg.Offset,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []SearchOrgRow
	for rows.Next() {
		var i SearchOrgRow
		if err := rows.Scan(
			&i.EntityKind,
			&i.EntityID,
			&i.Title,
			&i.Snippet,
			&i.Rank,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
