// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: tasks.sql

package db

import (
	"context"

	"github.com/google/uuid"
)

const createComment = `-- name: CreateComment :one
INSERT INTO comments (task_id, author_id, body)
VALUES ($1, $2, $3)
RETURNING id, task_id, author_id, body, created_at
`

type CreateCommentParams struct {
	TaskID   uuid.UUID `json:"task_id"`
	AuthorID uuid.UUID `json:"author_id"`
	Body     string    `json:"body"`
}

func (q *Queries) CreateComment(ctx context.Context, arg CreateCommentParams) (Comment, error) {
	row := q.db.QueryRow(ctx, createComment, arg.TaskID, arg.AuthorID, arg.Body)
	var i Comment
	err := row.Scan(
		&i.ID,
		&i.TaskID,
		&i.AuthorID,
		&i.Body,
		&i.CreatedAt,
	)
	return i, err
}

const createTask = `-- name: CreateTask :one

INSERT INTO tasks (org_id, project_id, title, status, position)
VALUES ($1, $2, $3, $4, $5)
RETURNING id, org_id, project_id, title, status, position, created_at, updated_at
`

type CreateTaskParams struct {
	OrgID     uuid.UUID `json:"org_id"`
	ProjectID uuid.UUID `json:"project_id"`
	Title     string    `json:"title"`
	Status    string    `json:"status"`
	Position  float64   `json:"position"`
}

// Tasks + comments — every task query scoped by org_id. (Chapter 8 / sqlc)
func (q *Queries) CreateTask(ctx context.Context, arg CreateTaskParams) (Task, error) {
	row := q.db.QueryRow(ctx, createTask,
		arg.OrgID,
		arg.ProjectID,
		arg.Title,
		arg.Status,
		arg.Position,
	)
	var i Task
	err := row.Scan(
		&i.ID,
		&i.OrgID,
		&i.ProjectID,
		&i.Title,
		&i.Status,
		&i.Position,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteTask = `-- name: DeleteTask :execrows
DELETE FROM tasks WHERE id = $1 AND org_id = $2
`

type DeleteTaskParams struct {
	ID    uuid.UUID `json:"id"`
	OrgID uuid.UUID `json:"org_id"`
}

func (q *Queries) DeleteTask(ctx context.Context, arg DeleteTaskParams) (int64, error) {
	result, err := q.db.Exec(ctx, deleteTask, arg.ID, arg.OrgID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getTaskByID = `-- name: GetTaskByID :one
SELECT id, org_id, project_id, title, status, position, created_at, updated_at
FROM tasks
WHERE id = $1 AND org_id = $2
`

type GetTaskByIDParams struct {
	ID    uuid.UUID `json:"id"`
	OrgID uuid.UUID `json:"org_id"`
}

func (q *Queries) GetTaskByID(ctx context.Context, arg GetTaskByIDParams) (Task, error) {
	row := q.db.QueryRow(ctx, getTaskByID, arg.ID, arg.OrgID)
	var i Task
	err := row.Scan(
		&i.ID,
		&i.OrgID,
		&i.ProjectID,
		&i.Title,
		&i.Status,
		&i.Position,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listCommentsByTask = `-- name: ListCommentsByTask :many
SELECT id, task_id, author_id, body, created_at
FROM comments
WHERE task_id = $1
ORDER BY created_at ASC
`

func (q *Queries) ListCommentsByTask(ctx context.Context, taskID uuid.UUID) ([]Comment, error) {
	rows, err := q.db.Query(ctx, listCommentsByTask, taskID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Comment
	for rows.Next() {
		var i Comment
		if err := rows.Scan(
			&i.ID,
			&i.TaskID,
			&i.AuthorID,
			&i.Body,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTasksByProject = `-- name: ListTasksByProject :many
SELECT id, org_id, project_id, title, status, position, created_at, updated_at
FROM tasks
WHERE org_id = $1 AND project_id = $2
  AND ($5::text IS NULL OR status = $5)
ORDER BY position ASC, created_at ASC, id ASC
LIMIT $3 OFFSET $4
`

type ListTasksByProjectParams struct {
	OrgID     uuid.UUID `json:"org_id"`
	ProjectID uuid.UUID `json:"project_id"`
	Limit     int32     `json:"limit"`
	Offset    int32     `json:"offset"`
	Status    *string   `json:"status"`
}

// A NULL status arg makes the status filter a no-op (any status).
func (q *Queries) ListTasksByProject(ctx context.Context, arg ListTasksByProjectParams) ([]Task, error) {
	rows, err := q.db.Query(ctx, listTasksByProject,
		arg.OrgID,
		arg.ProjectID,
		arg.Limit,
		arg.Offset,
		arg.Status,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Task
	for rows.Next() {
		var i Task
		if err := rows.Scan(
			&i.ID,
			&i.OrgID,
			&i.ProjectID,
			&i.Title,
			&i.Status,
			&i.Position,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateTask = `-- name: UpdateTask :one
UPDATE tasks SET title = $3, status = $4, position = $5, updated_at = now()
WHERE id = $1 AND org_id = $2
RETURNING id, org_id, project_id, title, status, position, created_at, updated_at
`

type UpdateTaskParams struct {
	ID       uuid.UUID `json:"id"`
	OrgID    uuid.UUID `json:"org_id"`
	Title    string    `json:"title"`
	Status   string    `json:"status"`
	Position float64   `json:"position"`
}

func (q *Queries) UpdateTask(ctx context.Context, arg UpdateTaskParams) (Task, error) {
	row := q.db.QueryRow(ctx, updateTask,
		arg.ID,
		arg.OrgID,
		arg.Title,
		arg.Status,
		arg.Position,
	)
	var i Task
	err := row.Scan(
		&i.ID,
		&i.OrgID,
		&i.ProjectID,
		&i.Title,
		&i.Status,
		&i.Position,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
