// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: users.sql

package db

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const createUser = `-- name: CreateUser :one

INSERT INTO users (email, name, password_hash)
VALUES ($1, $2, $3)
RETURNING id, email, name, password_hash, created_at
`

type CreateUserParams struct {
	Email        string `json:"email"`
	Name         string `json:"name"`
	PasswordHash string `json:"password_hash"`
}

type CreateUserRow struct {
	ID           uuid.UUID `json:"id"`
	Email        string    `json:"email"`
	Name         string    `json:"name"`
	PasswordHash string    `json:"password_hash"`
	CreatedAt    time.Time `json:"created_at"`
}

// Users — identity. The one table with no org_id. (Chapter 8 / sqlc)
func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) (CreateUserRow, error) {
	row := q.db.QueryRow(ctx, createUser, arg.Email, arg.Name, arg.PasswordHash)
	var i CreateUserRow
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.Name,
		&i.PasswordHash,
		&i.CreatedAt,
	)
	return i, err
}

const getUserByEmail = `-- name: GetUserByEmail :one
SELECT id, email, name, password_hash, created_at
FROM users
WHERE lower(email) = lower($1)
`

type GetUserByEmailRow struct {
	ID           uuid.UUID `json:"id"`
	Email        string    `json:"email"`
	Name         string    `json:"name"`
	PasswordHash string    `json:"password_hash"`
	CreatedAt    time.Time `json:"created_at"`
}

func (q *Queries) GetUserByEmail(ctx context.Context, lower string) (GetUserByEmailRow, error) {
	row := q.db.QueryRow(ctx, getUserByEmail, lower)
	var i GetUserByEmailRow
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.Name,
		&i.PasswordHash,
		&i.CreatedAt,
	)
	return i, err
}

const getUserByID = `-- name: GetUserByID :one
SELECT id, email, name, password_hash, created_at
FROM users
WHERE id = $1
`

type GetUserByIDRow struct {
	ID           uuid.UUID `json:"id"`
	Email        string    `json:"email"`
	Name         string    `json:"name"`
	PasswordHash string    `json:"password_hash"`
	CreatedAt    time.Time `json:"created_at"`
}

func (q *Queries) GetUserByID(ctx context.Context, id uuid.UUID) (GetUserByIDRow, error) {
	row := q.db.QueryRow(ctx, getUserByID, id)
	var i GetUserByIDRow
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.Name,
		&i.PasswordHash,
		&i.CreatedAt,
	)
	return i, err
}

const getUserPreferences = `-- name: GetUserPreferences :one

SELECT u.locale, u.timezone, COALESCE(o.default_locale, '') AS org_default_locale
FROM users u
LEFT JOIN organizations o ON o.id = $2
WHERE u.id = $1
`

type GetUserPreferencesParams struct {
	ID   uuid.UUID `json:"id"`
	ID_2 uuid.UUID `json:"id_2"`
}

type GetUserPreferencesRow struct {
	Locale           string `json:"locale"`
	Timezone         string `json:"timezone"`
	OrgDefaultLocale string `json:"org_default_locale"`
}

// Chapter 33 — the locale cascade's first two steps live in one row each.
// One query, because resolving a locale on every request must not be two.
func (q *Queries) GetUserPreferences(ctx context.Context, arg GetUserPreferencesParams) (GetUserPreferencesRow, error) {
	row := q.db.QueryRow(ctx, getUserPreferences, arg.ID, arg.ID_2)
	var i GetUserPreferencesRow
	err := row.Scan(&i.Locale, &i.Timezone, &i.OrgDefaultLocale)
	return i, err
}

const setUserPreferences = `-- name: SetUserPreferences :exec
UPDATE users SET locale = $2, timezone = $3 WHERE id = $1
`

type SetUserPreferencesParams struct {
	ID       uuid.UUID `json:"id"`
	Locale   string    `json:"locale"`
	Timezone string    `json:"timezone"`
}

func (q *Queries) SetUserPreferences(ctx context.Context, arg SetUserPreferencesParams) error {
	_, err := q.db.Exec(ctx, setUserPreferences, arg.ID, arg.Locale, arg.Timezone)
	return err
}
