// Package webhooks owns outgoing webhooks: the per-org endpoint registry, the
// delivery log, and the HMAC signing that lets a receiver prove a payload came
// from us. Delivery itself runs as a background job (see internal/jobs and the
// http layer's orchestration), so a down receiver never blocks a request.
//
// Course mapping: Chapter 24 — outgoing webhooks (signing, retries, DLQ). The
// chapter signs with HMAC-SHA256 over the JSON body and sends the header
// X-Beacon-Signature: sha256=<hex>; we match that exactly. Retries/backoff live
// in the jobs worker; this package owns the delivery rows it records.
//
// Course mapping: Chapter 8 — queries generated by sqlc (internal/db). Every
// webhook query is scoped by org_id; deliveries are keyed by webhook_id. The
// methods call the generated functions and map rows into Webhook / Delivery.
// UUIDs cross the boundary as text.
package webhooks

import (
	"context"
	"crypto/hmac"
	"crypto/rand"
	"crypto/sha256"
	"encoding/hex"
	"errors"
	"fmt"
	"time"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5"
	"github.com/jackc/pgx/v5/pgxpool"

	"beacon/internal/db"
)

// ErrNotFound is returned when no webhook matches in the caller's org.
var ErrNotFound = errors.New("webhook not found")

// SignatureHeader is the header carrying the HMAC over the body.
const SignatureHeader = "X-Beacon-Signature"

// Webhook is a registered outgoing endpoint for an org.
type Webhook struct {
	ID    string `json:"id"`
	OrgID string `json:"org_id"`
	URL   string `json:"url"`
	// Secret is the HMAC key a receiver uses to verify that a delivery really
	// came from Beacon. It is returned in full EXACTLY ONCE, in the response
	// to Create, and is redacted everywhere else — see toWebhook.
	//
	// omitempty is load-bearing: it is what makes the field optional in the
	// generated contract, so a client is told the truth about when to expect
	// it rather than being handed a type that promises it always arrives.
	Secret    string    `json:"secret,omitempty"`
	Events    []string  `json:"events" nullable:"false"`
	Active    bool      `json:"active"`
	CreatedAt time.Time `json:"created_at"`
}

// Delivery is one attempt-tracked delivery record (also the dead-letter row
// when status = 'dead').
type Delivery struct {
	ID          string     `json:"id"`
	WebhookID   string     `json:"webhook_id"`
	Event       string     `json:"event"`
	Status      string     `json:"status"`
	Attempts    int        `json:"attempts"`
	LastError   string     `json:"last_error"`
	CreatedAt   time.Time  `json:"created_at"`
	DeliveredAt *time.Time `json:"delivered_at,omitempty"`
}

// Sign computes the hex HMAC-SHA256 of body under secret, formatted as the
// chapter's "sha256=<hex>" header value.
func Sign(secret string, body []byte) string {
	mac := hmac.New(sha256.New, []byte(secret))
	mac.Write(body)
	return "sha256=" + hex.EncodeToString(mac.Sum(nil))
}

// Verify reports whether signature is a valid "sha256=<hex>" HMAC of body under
// secret. It compares in constant time. Receivers run this; we test against it.
func Verify(secret string, body []byte, signature string) bool {
	expected := Sign(secret, body)
	return hmac.Equal([]byte(expected), []byte(signature))
}

// newSecret returns a random 32-byte hex secret for a new webhook.
func newSecret() string {
	var b [32]byte
	_, _ = rand.Read(b[:])
	return hex.EncodeToString(b[:])
}

// Repo is the webhooks + deliveries repository backed by sqlc-generated queries.
type Repo struct {
	q *db.Queries
}

func NewRepo(pool *pgxpool.Pool) *Repo { return &Repo{q: db.New(pool)} }

// toWebhook converts a stored row for RETURNING TO A CLIENT, with the signing
// secret redacted.
//
// It used to copy the secret through, which meant listing webhooks handed the
// full HMAC key for every one of them to the caller — on every page load of the
// settings screen. That put a shared credential into browser memory, into any
// proxy that logs response bodies, into devtools, and into any client-side
// error report that captured a response. The UI meanwhile told the user the
// secret was shown once and could never be shown again, which was simply not
// true.
//
// Create is the one place it is legitimate to return, and it says so by using
// toWebhookWithSecret explicitly.
func toWebhook(h db.Webhook) Webhook {
	w := toWebhookWithSecret(h)
	w.Secret = ""
	return w
}

// toWebhookWithSecret includes the signing secret. Only Create may use it.
func toWebhookWithSecret(h db.Webhook) Webhook {
	// A nil Go slice marshals to JSON null, so a webhook subscribed to every
	// event — which is what an empty list means — would answer `"events":
	// null` while one subscribed to some answered `["task.created"]`. Two
	// spellings of the same idea is a distinction no client wants and every
	// client has to handle, so it is normalised here, once.
	events := h.Events
	if events == nil {
		events = []string{}
	}
	return Webhook{
		ID:        h.ID.String(),
		OrgID:     h.OrgID.String(),
		URL:       h.Url,
		Secret:    h.Secret,
		Events:    events,
		Active:    h.Active,
		CreatedAt: h.CreatedAt,
	}
}

// Create inserts a webhook with a freshly minted secret, scoped to the org.
func (r *Repo) Create(ctx context.Context, orgID, url string, events []string) (Webhook, error) {
	if events == nil {
		events = []string{}
	}
	oid, err := uuid.Parse(orgID)
	if err != nil {
		return Webhook{}, fmt.Errorf("webhooks.Create: parse org id: %w", err)
	}
	h, err := r.q.CreateWebhook(ctx, db.CreateWebhookParams{
		OrgID:  oid,
		Url:    url,
		Secret: newSecret(),
		Events: events,
	})
	if err != nil {
		return Webhook{}, fmt.Errorf("webhooks.Create: %w", err)
	}
	// The one legitimate place the signing secret leaves the server.
	return toWebhookWithSecret(h), nil
}

// ListByOrg returns an org's webhooks.
func (r *Repo) ListByOrg(ctx context.Context, orgID string) ([]Webhook, error) {
	oid, err := uuid.Parse(orgID)
	if err != nil {
		return []Webhook{}, nil
	}
	rows, err := r.q.ListWebhooksByOrg(ctx, oid)
	if err != nil {
		return nil, fmt.Errorf("webhooks.ListByOrg: %w", err)
	}
	out := make([]Webhook, 0, len(rows))
	for _, h := range rows {
		out = append(out, toWebhook(h))
	}
	return out, nil
}

// ActiveForEvent returns the org's active webhooks subscribed to event (a
// webhook with an empty events list subscribes to everything).
func (r *Repo) ActiveForEvent(ctx context.Context, orgID, event string) ([]Webhook, error) {
	oid, err := uuid.Parse(orgID)
	if err != nil {
		return []Webhook{}, nil
	}
	rows, err := r.q.ActiveWebhooksForEvent(ctx, db.ActiveWebhooksForEventParams{
		OrgID: oid,
		Event: event,
	})
	if err != nil {
		return nil, fmt.Errorf("webhooks.ActiveForEvent: %w", err)
	}
	out := make([]Webhook, 0, len(rows))
	for _, h := range rows {
		out = append(out, toWebhook(h))
	}
	return out, nil
}

// GetByID returns one webhook scoped to its org.
func (r *Repo) GetByID(ctx context.Context, orgID, id string) (Webhook, error) {
	wid, err := uuid.Parse(id)
	if err != nil {
		return Webhook{}, ErrNotFound
	}
	oid, err := uuid.Parse(orgID)
	if err != nil {
		return Webhook{}, ErrNotFound
	}
	h, err := r.q.GetWebhookByOrg(ctx, db.GetWebhookByOrgParams{ID: wid, OrgID: oid})
	if err != nil {
		if errors.Is(err, pgx.ErrNoRows) {
			return Webhook{}, ErrNotFound
		}
		return Webhook{}, fmt.Errorf("webhooks.GetByID: %w", err)
	}
	return toWebhook(h), nil
}

// Delete removes a webhook scoped to its org.
func (r *Repo) Delete(ctx context.Context, orgID, id string) error {
	wid, err := uuid.Parse(id)
	if err != nil {
		return ErrNotFound
	}
	oid, err := uuid.Parse(orgID)
	if err != nil {
		return ErrNotFound
	}
	n, err := r.q.DeleteWebhook(ctx, db.DeleteWebhookParams{ID: wid, OrgID: oid})
	if err != nil {
		return fmt.Errorf("webhooks.Delete: %w", err)
	}
	if n == 0 {
		return ErrNotFound
	}
	return nil
}

// CreateDelivery records a new pending delivery and returns its id. The worker
// updates this row as it attempts delivery.
func (r *Repo) CreateDelivery(ctx context.Context, webhookID, event string, payload []byte) (string, error) {
	wid, err := uuid.Parse(webhookID)
	if err != nil {
		return "", fmt.Errorf("webhooks.CreateDelivery: parse webhook id: %w", err)
	}
	id, err := r.q.CreateDelivery(ctx, db.CreateDeliveryParams{WebhookID: wid, Event: event, Payload: payload})
	if err != nil {
		return "", fmt.Errorf("webhooks.CreateDelivery: %w", err)
	}
	return id.String(), nil
}

// MarkDeliverySuccess flips a delivery to success and stamps delivered_at.
func (r *Repo) MarkDeliverySuccess(ctx context.Context, id string, attempts int) error {
	did, err := uuid.Parse(id)
	if err != nil {
		return fmt.Errorf("webhooks.MarkDeliverySuccess: parse id: %w", err)
	}
	return r.q.MarkDeliverySuccess(ctx, db.MarkDeliverySuccessParams{ID: did, Attempts: int32(attempts)})
}

// MarkDeliveryFailed records a failed attempt; dead = true parks it in the DLQ.
func (r *Repo) MarkDeliveryFailed(ctx context.Context, id string, attempts int, lastError string, dead bool) error {
	status := "failed"
	if dead {
		status = "dead"
	}
	did, err := uuid.Parse(id)
	if err != nil {
		return fmt.Errorf("webhooks.MarkDeliveryFailed: parse id: %w", err)
	}
	return r.q.MarkDeliveryStatus(ctx, db.MarkDeliveryStatusParams{
		ID:        did,
		Status:    status,
		Attempts:  int32(attempts),
		LastError: lastError,
	})
}

// GetWebhook is used by the delivery worker (resolves URL + secret by id).
func (r *Repo) GetWebhook(ctx context.Context, id string) (Webhook, error) {
	wid, err := uuid.Parse(id)
	if err != nil {
		return Webhook{}, ErrNotFound
	}
	h, err := r.q.GetWebhook(ctx, wid)
	if err != nil {
		if errors.Is(err, pgx.ErrNoRows) {
			return Webhook{}, ErrNotFound
		}
		return Webhook{}, fmt.Errorf("webhooks.GetWebhook: %w", err)
	}
	return toWebhook(h), nil
}

// Service holds the webhook business rules.
type Service struct {
	repo *Repo
}

func NewService(repo *Repo) *Service { return &Service{repo: repo} }

// Register creates a new webhook for the org.
func (s *Service) Register(ctx context.Context, orgID, url string, events []string) (Webhook, error) {
	return s.repo.Create(ctx, orgID, url, events)
}

// List returns the org's webhooks.
func (s *Service) List(ctx context.Context, orgID string) ([]Webhook, error) {
	return s.repo.ListByOrg(ctx, orgID)
}

// Delete removes a webhook from the org.
func (s *Service) Delete(ctx context.Context, orgID, id string) error {
	return s.repo.Delete(ctx, orgID, id)
}

// ActiveForEvent is used by the http orchestration to find which endpoints
// should receive a given event.
func (s *Service) ActiveForEvent(ctx context.Context, orgID, event string) ([]Webhook, error) {
	return s.repo.ActiveForEvent(ctx, orgID, event)
}

// CreateDelivery records a pending delivery (called when enqueuing a job).
func (s *Service) CreateDelivery(ctx context.Context, webhookID, event string, payload []byte) (string, error) {
	return s.repo.CreateDelivery(ctx, webhookID, event, payload)
}
